### ISSUE TITLE
Souffle Licensing

### ISSUE THREAD

**Issue by scyptnex** [souffle-lang/souffle#100]
Miscelaneous licensing issues for Souffle.
Enhances issue #77 for the next version, and addresses limitations of #99 .
Not all of this needs to be done

* create a `licenses/` directory
* Move the `LICENSE` to `licenses/souffle-UPL`
* Add __full__ copies of all the licenses for all the souffle dependencies to `licenses/<DEPENDENCY>-<LICENSE>`
* Fix some sources currently license to Oracle (without UPL)
    * e.g. `src/souffle-complie.in`
* Fix the headers of all souffle sources to contain the license:
```
Souffle version <VERSION>
Copyright (c) <YEARS...> Oracle and/or it's affiliates.  All rights reserved.
Licensed under the Universal Permissive License v 1.0 as shown at:
 - https://opensource.org/licenses/UPL
 - souffle/licenses/souffle-UPL
```
* include above license in `licenses/souffle-UPL.header`

**Comment by icesparrow** [comment]
I thought this issue was for the upcoming release, but it is actually tagged with 1.1.0 Should we postpone it?

**Comment by icesparrow** [comment]
Ok, I was messing around with some of the tools for managing/checking licenses and copyright notices and it turned out that in Debian/Ubuntu there is a tool called `licensecheck` for testing whether there are licenses in the source code, so based on the output of the tool we have a few different copyright across different source files. Namely:

- `2013, 2014, Oracle and/or its affiliates`
- `2013, 2014, Oracle and/or its affiliates. All rights reserved`
- `2013, 2014, Oracle and/or its affiliates. All Rights reserved`
- `2013, 2015, Oracle and/or its affiliates. All rights reserved`
- `2013, Oracle and/or its affiliates. All rights reserved`
- `2015, Oracle and/or its affiliates`
- `2015, Oracle and/or its affiliates. All rights reserved`

So how do we go about years, should it be 2016, or <the first year> - 2016, or leave the years as they are now?

**Comment by scyptnex** [comment]
Year should reflect dates when the copyright holder added IP to the material, so they wont all be the same for the source code, though we'll be long dead before this becomes meaningful

I'd like to use the above license template on all Oracle licensed sources, but some of them have Oracle's old license, which i'm not allowed to change, so we're getting Nathan Keynes' permission for that.

I moved this issue to 1.1.0 because licensing does not affect backwards compatibility, and we have better things to worry about now.
