### ISSUE TITLE
RAM Refactoring - Null pointers

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#1000]
At the moment, we use null-pointers to model behaviour. That leads to complication in the visitor patterns and is not good practice. To simplify code, I suggest that all RAM pointers stored in the RAM must have non-null values. 

For example, the pattern array in RamIndexSearchRelation uses null-pointers to model an unspecified value for an attribute of the relation. I would suggest to have the RamUndefined as a sub-class to model this behaviour.

As a consequence, we can use in all access methods aliases rather than pointers.

**Comment by HerbertJordan** [comment]
Null pointers should be prohibited in the RAM or AST structure since their interpretation is unclear and -- as @b-scholz pointed out -- they cause problems with infrastructure tooling. Using a special object to implement/represent the null value behavior is known as the [null pattern](https://en.wikipedia.org/wiki/Null_object_pattern), and in my experience, following this pattern is a good idea.

One possibility to enforce this design principle would be to use a specialized Node-Reference type as a unique_ptr replacement, ensuring that the referenced element is always non-null. This would make the intent clearer, and help avoiding mistakes.

**Comment by b-scholz** [comment]
Can you give us the coding C++ template for such a unique_ptr reference? 

Ideally,  we would have also an ensured way to create new objects using make_unique only. However, that might be harder to achieve in C++.
