### ISSUE TITLE
Building without RTTI

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1080]
When trying to build Souffle with `-fno-rtti`, compilation fails on [this line](https://github.com/souffle-lang/souffle/blob/master/src/Util.h#L775):
```c++
    ss << typeid(T).name();
```
Since some significant projects use `-fno-rtti` (notably, LLVM) it would be nice to be able to avoid it with a configuration flag when building Souffle.

**Comment by b-scholz** [comment]
Is there a way to build a (dynamic) library from the Souffle generated code so that you can mix RTTI with non-RTTI components? 

I found following links:
https://www.boost.org/doc/libs/1_64_0/doc/html/boost_typeindex/mixing_sources_with_rtti_on_and_.html
https://stackoverflow.com/questions/1490593/mixing-rtti-flags-in-c
