### ISSUE TITLE
Build instructions fail on Debian

### ISSUE THREAD

**Issue by pnappa** [souffle-lang/souffle#1085]
Hi, the instructions found at https://souffle-lang.github.io/install#debianubuntu-systems don't seem to work on my Debian Stretch system.

First, the apt-add-repository command isn't installed by default in Debian - you need to install `software-properties-common`.

Second, after following those instructions, no package named souffle is found (nor anything in the cache including those words, `sudo apt-cache search souffle`).

Perhaps we may find it more robust to tell people to grab the deb from the releases tab and install with `dpkg -i $debname.deb`? That installs it correctly on my system.

**Comment by mmcgr** [comment]
I updated the instructions to use
```
echo "deb https://dl.bintray.com/souffle-lang/deb-unstable bionic main"|sudo tee -a /etc/apt/sources.list
```
instead of add-apt-repository.

add-apt-repository has another problem in that it adds a line to sources.list using the release name for the current distribution. This still fails on Debian since we don't have a repository specific for each Debian distribution. This could be revisited in future if we ever properly support all distributions - currently we actually only support one and rename it, which seems an imperfect solution.

With regard to linking people to the deb on the releases tab - that works, but will not update the package. The benefit of adding a repository is that the soufflé install is updated.
