### ISSUE TITLE
Provide REPL

### ISSUE THREAD

**Issue by XVilka** [souffle-lang/souffle#1113]
Like almost any other Datalog and Prolog systems.

**Comment by b-scholz** [comment]
Souffle works differently - it only achieves the speed because we assume that the ruleset is constant (known at the start). 

However, there is a query system integrated - it is called the povenance. 

You can enable provenance with the ```-t explain ``` option. 

You find more information there:
https://souffle-lang.github.io/provenance

**Comment by lyndonhenry** [comment]
I agree with @b-scholz, maintaining a decent REPL isn't exactly in line with how Souffle is ought to be used. That said, if we want to ease the learning curve for new users, it might be a good idea. So here's a quick hack of a solution. 

We add a new `--repl` option to Souffle, which calls a script something like the following:

~~~
#!/bin/bash
echo > ~/.souffle_1.tmp
echo > ~/.souffle_2.tmp
while true; do
    IFS= read -r -p "$ " LINE
    echo "${LINE}" >> ~/.souffle_1.tmp;
    souffle -F- -D- ~/.souffle_1.tmp && \
        cat ~/.souffle_1.tmp > ~/.souffle_2.tmp || \
        cat ~/.souffle_2.tmp > ~/.souffle_1.tmp;
done;
~~~

That script works as is if you want to copy paste it. The only question really is whether a bad REPL is better than no REPL at all.
