### ISSUE TITLE
This is a question on simple arithmetic

### ISSUE THREAD

**Issue by freedafeng** [souffle-lang/souffle#1301]
Please disregard the following question. I figured out. No problem any more. Thanks.

.decl edge(x:number, y:number)
.input edge

.decl C(x:number, y:number)
C(a,c) :- a = c.

Then I ran
$ souffle -F. -D. filename.dl 
Error: Ungrounded variable a in file **.dl at line 5
C(a,c) :- a = c.
--^--------------
Error: Ungrounded variable c in file **.dl at line 5
C(a,c) :- a = c.
----^------------
2 errors generated, evaluation aborted

I copied the code from the tutorial. What's wrong with this simple code? why do 'a' and 'c' need to be grounded at first palce? 

I then added the following,
C(a,c) :- edge(a, c).

It's still a no go.

**Comment by lyndonhenry** [comment]
*As I'd written the following before the question was amended, I'll leave the answer here in case it was useful to others.*

Here's how I like to think about it.

The line

```
.decl C(x:number, y:number)
```

This says "I declare C to be a relation, a finite set of pairs of numbers."

Then this line says 

```
C(a,c) :- a = c.
```

This says "C contains all pairs of numbers such that a = c".

Now, the set of all pairs of equal numbers is infinite. C, as a relation, is finite. Hence, C cannot be this former set. 

The "ungroundedness" comes from the fact that `a` and `c` have to come from some other finite set (i.e. another relation). Otherwise, their values could only be assigned from their domain (numbers) which produces our earlier infinite set. 

If we do 

```
C(a,c) :- a = c, B(a), B(c).
```

Where B is

```
.decl B(x:number)
B(0).
B(1).
B(2).
...
```

Then things work fine, as `a` and `c` are "grounded" in `B`, BUT the relation C will only have pairs of numbers that occur in B.

**Comment by freedafeng** [comment]
That's what I figured. Thanks Lyndonhenry for confirming it. 

If anyone wondered, I changed the clause to,
C(a,c) :- a = c, (edge(a, _); edge(_, c)).
