### ISSUE TITLE
Proposal: Style change - Single-line case statements.

### ISSUE THREAD

**Issue by ohamel-softwaresecure** [souffle-lang/souffle#1407]
We've many large switch statements with trivial case bodies. These get annoying to read when they're two or three lines instead of one. Enabling `AllowShortCaseLabelsOnASingleLine` would solve this. Only downside is that `clang-format` doesn't yet know how to align the single-line case bodies.

**Comment by b-scholz** [comment]
A more prudent software engineering approach/linting would help. @mmcgr has improved linting styles for Souffle. Perhaps we can extend the linting templates for Souffle to enforce these coding styles.

**Comment by mmcgr** [comment]
I'm okay with this. I don't think it's a good idea in general as it can generate a solid block of code that you can easily look past and miss the errors/complications inside it. We have large blocks of switch statement with very similar, and simple, code, though.

So I think we can allow the single line case statements, and trust the developer to get it right.

Note this is actually very similar to the existing treatment of control flow. We have a few cases where there is a block of `if (foo) return bar`, probably in the same file as the big switch statements. Since it's a `return/break`, and formatting is enforced, there's not much scope for error. On the downside, nothing enforces the `return/break` limitation. (If there was an option for AllowShortIfStatementsOnASingleLineButOnlyIfTheyAreAReturnOrABreak, I would use it.)

**Comment by ohamel-softwaresecure** [comment]
Concur regarding `AllowShortIfStatementsOnASingleLineButOnlyIfTheyAreAReturnOrABreak`. Perhaps we could make a PR to clang-format in the future...

**Comment by mmcgr** [comment]
I'm less sure now, since clang-format enforces the single line even when it is less clear, such as when it means a mix of multi-line and single-line. 

#1416 shows what the result will look like.

**Comment by ohamel-softwaresecure** [comment]
Looks like there's only a handful of those and `clang-format` appears to format `{}` blocks as multiline. Edit those to use `{}` whilst we wait for a `AllowShortIfStatementsOnASingleLineButOnlyIfTheyAreAReturnOrABreak`? Or defer until `AllowShortIfStatementsOnASingleLineButOnlyIfTheyAreAReturnOrABreak` is a feature?
