### ISSUE TITLE
Better/alternative way of embedding Souffle programs (in other languages)?

### ISSUE THREAD

**Issue by luc-tielen** [souffle-lang/souffle#1466]
Hi, I was wondering if it is possible to change / add a different interface for embedding Souffle programs in other languages?

I've built the [souffle-haskell](https://github.com/luc-tielen/souffle-haskell) library so that Haskellers can easily integrate with Souffle, but right now it involves a hack to get the C++ code to initialize properly before the Haskell code calls into it. The hack is needed because (I think) there is some static code that is initialized before even a "main" function would run. I've tried all kinds of workarounds but the only thing that I found that works is injecting C++ code directly into a Haskell module (which feels just wrong).

Here's an example snippet of some C++ code generated by `souffle` that I use in the test suite of my library (with the line annotated what I think causes this issue):
```c++
#ifdef __EMBEDDED_SOUFFLE__
class factory_Sf_path : public souffle::ProgramFactory {
  SouffleProgram *newInstance() { return new Sf_path(); };

public:
  factory_Sf_path() : ProgramFactory("path") {}
};
static factory_Sf_path __factory_Sf_path_instance;  // this line
}
#else
// ... more code
#endif
```

Idk the reasons why this needs to be statically initialized and why it involves quite some bookkeeping (factory / registry approach)?
Ideally, I would prefer an interface where I can just `new` a souffle program object on the C++ side so that I have full control over it (and free/delete it when I no longer need it).

If you need any more information, please let me know.

**Comment by mmcgr** [comment]
The problem you're having is probably because the initialisation order across compilation units is undefined.

I believe the factory method exists so you have access to the implementation without a corresponding header file to describe the object. The static initialisation is required so the factory implementation is available to other objects when they ask for it (should the linker gods smile on your ordering).

Would it be feasible to include the synthesised cpp file instead?

**Comment by luc-tielen** [comment]
Thanks for the explanation, this clarifies why the design is the way it is. 

I don't think it is feasible, eventually the Haskell code calls [this](https://github.com/luc-tielen/souffle-haskell/blob/master/cbits/souffle.cpp#L6-L9). The library does not know beforehand which souffle program it's going to call, so it only has a runtime string describing the program it wants to run. (This is where the factory approach does help.)

I'm fairly sure in C++ you can't go from a runtime string to a class definition to then proceed to `new` that object (unless you use that factory approach). Or the same for a string -> function pointer (this would allow me to call `SouffleProgram *newInstance_path() { return new Sf_path; }` directly (for example). 

But maybe it's possible to load the generated .cpp file as a DLL and then call the function dynamically? (See last answer on [stackoverflow](https://stackoverflow.com/questions/19473313/how-to-call-a-function-by-its-name-stdstring-in-c)). FYI I never tried this before so idk how hard this would be to achieve in Haskell. I will try this out later and post results back here.

**Comment by yanniss** [comment]
I know about C++ linking but I was confused by the above. I think the issues of invoking Souffle (the language implementation) and a Souffle Datalog (compiled into C++) program are separate. If the header file (souffle.h, presumably) is included anyway, I don't see why one can't initialize a `factory_Sf_path` object when it's needed, instead of relying on the statically-initialized one. Is there code that forces this to be a singleton?

DLLs certainly also work, for going from a string to a function pointer. But if the Souffle API already offers a full-featured "init and run a compiled souffle-datalog program" indirection, I cannot see involving a DLL for the generated .cpp as the right solution.

And sorry if the above isn't helping--I haven't done any of this, just thinking aloud based on what I just read.

**Comment by csabahruska** [comment]
I believe it is a linker issue in Haskell. To me it seems that the static global factory instance got removed by the linker from the final executable.

**Comment by csabahruska** [comment]
if you add the following to haskell-souffe's cabal:
```
ghc-options: -fwhole-archive-hs-libs
```
The static factory instance asm secion will be kept in the final executable and it will work without the template haskell embedding. So I believe the current souffle C++ interface is absolutely OK.
(sorry for the non C++ related things)

**Comment by csabahruska** [comment]
I investigated the issue further and found the following.
Here is an example souffle generated c++ code:
```cpp
#ifdef __EMBEDDED_SOUFFLE__
class factory_Sf_ext_stg_liveness : public souffle::ProgramFactory {
  SouffleProgram *newInstance() { return new Sf_ext_stg_liveness(); };

public:
  factory_Sf_ext_stg_liveness() : ProgramFactory("ext_stg_liveness") {}
};
static factory_Sf_ext_stg_liveness __factory_Sf_ext_stg_liveness_instance;
}
#else
}
int main(int argc, char **argv) {
```
This is what souffle generates ATM. But unfortunately the whole `__factory_Sf_ext_stg_liveness_instance` part gets eliminated by the linker because of the `--gc-sections` option that GHC uses. And in case of Haskell it is a must due to the large binaries.

I managed to retain `__factory_Sf_ext_stg_liveness_instance` by adding the `-Wl,--undefined=__factory_Sf_ext_stg_liveness_instance` linker option to the executable command line. But it needs two changes regarding the static instance symbol:
- it must be a C symbol (no name mangling) to make it easy to refer
- it must not use the `static` qualifier, otherwise the symbol reference does not work

Here is the same code with the proposed changes:
```cpp
#ifdef __EMBEDDED_SOUFFLE__
class factory_Sf_ext_stg_liveness : public souffle::ProgramFactory {
  SouffleProgram *newInstance() { return new Sf_ext_stg_liveness(); };

public:
  factory_Sf_ext_stg_liveness() : ProgramFactory("ext_stg_liveness") {}
};
}

// changed part:
extern "C" {
souffle::factory_Sf_ext_stg_liveness __factory_Sf_ext_stg_liveness_instance;
}

#else
}
int main(int argc, char **argv) {
```
