### ISSUE TITLE
Make new release?

### ISSUE THREAD

**Issue by luc-tielen** [souffle-lang/souffle#1481]
Hi, I was wondering if it's possible to do a (patch) release again? 

It's been a while since the last one and https://github.com/souffle-lang/souffle/pull/1476 contains a fix I need for [souffle-haskell](https://github.com/luc-tielen/souffle-haskell).

Thanks in advance!

**Comment by mmcgr** [comment]
We were building up to a 2.0 release, with a few issues blocking the main changes we had been thinking of.

Still, a summary of the 203 PRs made since the last release:
* Query interface for provenance (yuli6313)
* Removed MPI support (b-scholz)
* Removed bddbddb and logicblox converters (b-scholz)
* Removed checkpointed evaluation (b-scholz)
* Extended inlining support (azreika)
* Fixes for AST/RAM printing
* Added AST debug output for final 'optimised datalog' (mmcgr)
* Added RAM debug output
* Updated man pages (darth-tytus/mmcgr)
* More useful debug output (mmcgr)
* Much more useful debug output (ohamel-softwaresecure)
* Interpreted souffle performance improvements (XiaowenHu96)
* Improved version output (mmcgr)
* Added support for floats and unsigned ints (darth-tytus)
* Improved testing (yuli6313/mmcgr)
* Added support for Record I/O (darth-tytus)
* Simplified error and warning messages (mmcgr)
* Added bitshift operators (ohamel-softwaresecure)
* Added support for polymorphic constants (darth-tytus)
* Improved aggregate performance (rdowavic)
* Added support for `as(arg, type)` (darth-tytus)
* Extensive refactoring of AST, RAM, utilities, and other bits (b-scholz and others)
* Various bugfixes

It does seem like past time for a new release.

**Comment by b-scholz** [comment]
Indeed - we should issue a new release soon.  My main concern is that the new type system for functors needs to revisited/checked again; otherwise, I am ok to go ahead with the new release.

Martin - also the legacy flag is important (not so much from the implementation viewpoint but from the user's viewpoint to run their old codes).

**Comment by mmcgr** [comment]
* Added `--legacy` flag to allow use of legacy options
* Added `--show [...]` flag to show various extra bits of information for debugging/optimising
* Added `--no-warn` flag to disable warnings

**Comment by b-scholz** [comment]
Also, we have bugs in aggregates and magic set transformations.

**Comment by luc-tielen** [comment]
Well, another possibility is to create a branch starting from last tag (v1.7.1), then only apply the fix from my pull request and release that as 1.7.2. 
This gives you less pressure for all the other things 😃

**Comment by b-scholz** [comment]
This is less preferred because we would need to start maintaining several release branches. Ideally, we have a linear line of releases.

When do you want to have the new release issued?

**Comment by luc-tielen** [comment]
Well, you could branch it off from v1.7.1 just to have a small diff and then merge it back into master (should be no diff since that already contains my fix). As long as a "hotfix" happens rarely and is not the norm, it should be fine?

I have no preferred release date, but I do have an [open PR](https://github.com/luc-tielen/souffle-haskell/pull/13) that I can't merge as long as I can't tell people to use 1.7.2 (or some other new version).

**Comment by b-scholz** [comment]
I will talk to the team.

**Comment by langston-barrett** [comment]
I am also looking forward to the next release of Souffle, which has fixes for a few bugs that make profiling more difficult on my codebase. Thanks as always for your responsiveness @b-scholz!

**Comment by mmcgr** [comment]
We want to get some fixes to the magic set transformation in, which is both an improvement and a fix for a few issues. @azreika expects that to be done by the 19th. So, Souffle 2.0 is planned for the 19th (ish).

**Comment by luc-tielen** [comment]
Thanks for the update!

**Comment by luc-tielen** [comment]
@b-scholz @mmcgr I think this issue can be closed now that the 2.0.0 release is out? I will try and update my library sometime soon to see if it is still compatible 😅.

**Comment by luc-tielen** [comment]
Closing this, tried it out in souffle-haskell and the issue I was having is now fixed. Thanks for this!
