### ISSUE TITLE
Multiple versions of Souffle on the same machine

### ISSUE THREAD

**Issue by nevillegrech** [souffle-lang/souffle#1490]
Is it possible to have multiple versions of Souffle co-exist within the same machine? It seems possible to do so if using interpreted mode, as follows:

```
./configure --program-suffix=2
sudo make install
souffle2 --help
```

However the compiled modes of different versions use different versions of header files and objects. In addition, they both seem to call the same `souffle-compile` command, ignoring the --program-suffix / --program-prefix configuration.

**Comment by b-scholz** [comment]
This must be an issue related to your installation. I believe that you pick up the wrong `souffle-compile` because `souffle-compile` determines its header files via 
```
HEADER_DIR=$(dirname $0)/../include
```

It seems that in your installation, `souffle2` calls `souffle-compile` from the first `souffle` installation. 

A workaround for your setup could be to extend the name of souffle-compile with the suffix in main.cpp and instruct automake accordingly.  
```
auto findCompileCmd = [&] {
                auto cmd = ::findTool("souffle-compile", souffleExecutable, ".");
                /* Fail if a souffle-compile executable is not found */
                if (!isExecutable(cmd)) {
                    throw std::runtime_error("failed to locate souffle-compile");
                }
                return cmd;
            };
```

Do you want to give it a try?

**Comment by mmcgr** [comment]
You could also install each version of souffle to its own directory. I think that wouldn't require any other changes, although you would need to use the full path to the souffle version.

**Comment by b-scholz** [comment]
That is right - basically, if you switch the PATH variable accordingly, no change is required.

**Comment by mmcgr** [comment]
`souffle-compile` is found relative to `souffle`. The headers are found relative to `souffle-compile`. If each version of `souffle` is in its own directory then it should just work.

The standard search order for headers is current directory, paths given with `-I`, then system directories. The souffle headers are added in `souffle-compile` with `-I` so that should be reliable.

**Comment by b-scholz** [comment]
Can we close this issue?
