### ISSUE TITLE
When generating code, "failed to locate souffle-compile" if there is a file named "souffle" in working directory

### ISSUE THREAD

**Issue by ekzhang** [souffle-lang/souffle#1537]
When compiling a Datalog program with `souffle -o tc tc.dl`, I'm getting the error "failed to locate souffle-compile". I am on Ubuntu 20.04, with Souffle installed using the apt repository - this occurs on both the latest stable and unstable releases for version 2.0.0.

I checked that souffle and souffle-compile are both on my path, at `/usr/bin/souffle[-compile]`. It seems like this command works most of the time, but I'm only getting the error when I have another file named "souffle" in my working directory.

How I came across this behavior:
```bash
$ touch tc.dl
$ souffle -o souffle tc.dl # Works!
$ souffle -o souffle tc.dl
failed to locate souffle-compile
```

Another way to reproduce:
```bash
$ touch prog1.dl prog2.dl
$ souffle -o prog1 prog1.dl # Works!
$ touch souffle
$ chmod +x souffle
$ souffle -o prog2 prog2.dl
failed to locate souffle-compile
```

**Comment by mmcgr** [comment]
So I misread this, my misreading was actually also an issue, and I fixed that.

I'll update my PR to address this issue as well. Currently souffle looks for the path it was called from first - great if it's a full path, but not so good if it's just 'souffle' since that now checks the current directory first. The new version will check if it has path components and return it if so. Otherwise it will then iterate through the PATH variable until it finds the binary it's looking for.

**Comment by mmcgr** [comment]
This is fixed in my testing. Does the latest unstable release work for you? (Or at least, the latest release a couple of hours from the date of this post.)
