### ISSUE TITLE
Profiler issues

### ISSUE THREAD

**Issue by yanniss** [souffle-lang/souffle#167]
The profiler (and souffle -p) currently have several issues, though I recall profiling successfully in the past.

-souffle -p does not work in compile mode (makes it much less useful). The documentation claims this works but it does not even output a log.

-souffle-profile does not work for incomplete logs. But one typically needs to profile programs that run for long.

-I suspect souffle-profile also has issues with programs containing richer syntax (components?). E.g., I don't see why it fails on this:
Error: Invalid log file format:
@t-recursive-relation;SoundMayPhase1.InvocationActualFormalAssignment;logic/analyses/sound-may-point-to/analysis.dl [532:3-532:113];@n-recursive-rule;SoundMayPhase1.AccessPathNotSetByPredecessorBB;0;logic/analyses/sound-may-point-to/analysis.dl [1104:3-1110:53];SoundMayPhase1.AccessPathNotSetByPredecessorBB(?ap,?pred) :-     SoundMayPhase1.AccessPathRelevantToMethod(?ap,?meth),    SingleFieldAccessPath(?fld,?ap),    Instruction_Method(?pred,?meth),    BasicBlockBegin(?pred),    !SomePathFromFirstInstructionAssignsField(?pred,?fld),    !SomePathFromFirstInstructionCallsMethod(?pred).;0.00023357
Error: File cannot be loaded

-souffle-profile crashes very often. I currently can't profile programs that worked fine in the past. E.g., I get:

> rul 
> Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Double
>         at com.oracle.souffleprof.ProgramRun.formatTable(ProgramRun.java:505)
>         at com.oracle.souffleprof.Tui.rul(Tui.java:382)
>         at com.oracle.souffleprof.Tui.runCommand(Tui.java:66)
>         at com.oracle.souffleprof.Tui.runProf(Tui.java:150)
>         at com.oracle.souffleprof.Cli.parse(Cli.java:102)
>         at com.oracle.souffleprof.SouffleProf.main(SouffleProf.java:18)

Please let me know if you can't reproduce any of the above, but they are so widespread in what I observe that I think it will be easy.

**Comment by psubotic** [comment]
Hi, Yannis, thanks for letting us know. I have experienced the same. We
will fix this ASAP.

**Comment by souffle-lang** [comment]
Yannis - the second issue should work, i.e., working with incomplete profiles. The profiler has the option -l. Although not well documented, it should be able to deal with incomplete profiles. 

The last problem is interesting. It seems that the profiler cannot parse the Datalog statement well because ";" is used as a separator in the data format. However, with the latest language extension we use ";" as a Soufflé language element. I will have a quick look today to fix this as well. The quick fix is to change the output so that semicolon won't appear in the string representation of the Datalog rule.

**Comment by b-scholz** [comment]
I noticed that the script invoking the jar files causes troubles. 

It is better to directly invoke the profiler with 

java souffleprof.jar  -l -f <profile>
