### ISSUE TITLE
Issue with generative functors/ranges 

### ISSUE THREAD

**Issue by SamArch27** [souffle-lang/souffle#1671]
There is an issue with Souffle for both interpreter and synthesiser modes for when multiple generative functors/ranges have identical bounds.

The following program:

    .decl A(x:number, y:number)
    .output A

    A(x,y) :- x = range(1,3), y = range(1,3).

Should produce { (1,1), (1,2), (2,1), (2,2) } but instead it produces { (1,1), (2,2) }.

If the ranges are not identical then the output from Souffle is correct (the cross product of the ranges).

The RAM for the program is:

    PROGRAM
     DECLARATION
      A(x:i:number,y:i:number) 
     END DECLARATION
     SUBROUTINE stratum_0
      BEGIN_DEBUG "A(range(1,3),range(1,3)).\nin file /home/sarc9328/benchmarking/test.dl [4:1-4:42]"
       QUERY
        RANGE(number(1),number(3)) INTO t0
         PROJECT (t0.0, t0.0) INTO A
      END_DEBUG
      IO A (IO="file",attributeNames="x\ty",name="A",operation="output",output-dir=".",params="{\"records\": {}, \"relation\": {\"arity\": 2, \"auxArity\": 0, \"params\": [\"x\", \"y\"]}}",types="{\"ADTs\": {}, \"records\": {}, \"relation\": {\"arity\": 2, \"auxArity\": 0, \"types\": [\"i:number\", \"i:number\"]}}")
     END SUBROUTINE
     BEGIN MAIN
      CALL stratum_0
     END MAIN
    END PROGRAM

It looks like somewhere in the AST/RAM the duplicate range gets removed.

**Comment by SamArch27** [comment]
In ast2ram/Ast2RamTranslator.cpp we find:

    // add aggregation functions
        visitDepthFirstPostOrder(clause, [&](const ast::Argument& arg) {
            // returns the write-location for this generator (or none if an equiv arg was already seen)
            auto addGenerator = [&]() -> std::optional<int> {
                // The by-value compare means that we're effectively doing CSE for any
                // generator args during code-gen. This is a weird place to do this.
                if (any_of(generators, [&](auto* x) { return *x == arg; })) return {};
                generators.push_back(&arg);
    
                int aggLoc = level++;
                valueIndex.setGeneratorLoc(arg, Location({aggLoc, 0}));
                return aggLoc;
            };

The line:

    if (any_of(generators, [&](auto* x) { return *x == arg; })) return {};

Will remove any duplicate aggregates/ranges.
After commenting out this line I get the RAM:

    PROGRAM
     DECLARATION
      A(x:i:number,y:i:number) 
     END DECLARATION
     SUBROUTINE stratum_0
      BEGIN_DEBUG "A(range(1,3),range(1,3)).\nin file /home/sarc9328/benchmarking/test.dl [4:1-4:42]"
       QUERY
        RANGE(number(1),number(3)) INTO t0
         RANGE(number(1),number(3)) INTO t1
          PROJECT (t0.0, t0.0) INTO A
      END_DEBUG
      IO A (IO="file",attributeNames="x\ty",name="A",operation="output",output-dir=".",params="{\"records\": {}, \"relation\": {\"arity\": 2, \"auxArity\": 0, \"params\": [\"x\", \"y\"]}}",types="{\"ADTs\": {}, \"records\": {}, \"relation\": {\"arity\": 2, \"auxArity\": 0, \"types\": [\"i:number\", \"i:number\"]}}")
     END SUBROUTINE
     BEGIN MAIN
      CALL stratum_0
     END MAIN
    END PROGRAM

Which is still incorrect as the project statement should have (t0.0, t1.0).
I think the issue stems from ast2ram/Ast2RamTranslator.h:

    const Location& getGeneratorLoc(const ast::Argument& arg) const {
                // search list
                for (const auto& cur : arg_generator_locations) {
                    if (*cur.first == arg) {
                        return cur.second;
                    }
                }
    
                fatal("arg `%s` has no generator location", arg);
            }

I'm guessing that this lookup will return the location of the first generator which matches the AST representation.
Therefore, when we have two ranges which are identical it returns the first one (the one belonging to t0).

I had a discussion with @azreika about this and he mentioned that aggregates are pure and therefore if there are identical aggregates then either one can be used. However, with ranges, allowing iteration requires that the range keeps internal state between iterations. Since identical ranges may be in different states of their iteration they can't be treated as interchangeable like aggregates can be. 

It would be good to have a discussion about what changes should be made to ensure ranges have the correct semantics.

**Comment by azreika** [comment]
Possibly related bug: when provenance is run on some programs with ranges, Souffle crashes during Ast2Ram translation with an assertion error. The problem does not appear with the above program, but does in the following:

```
.decl A(x:number, y:number)
.output A

A(x,y) :- x = range(1,3), y = range(1,3), x + y = 3.
```
with the error:
```
arg `range(1,3)` has no generator location
souffle: ./include/souffle/utility/MiscUtil.h:195: void souffle::fatal(const char*, const Args& ...) [with Args = {souffle::ast::Argument}]: Assertion `false && "fatal error; see std err"' failed.
```
The difference is likely because of their appearance in a functor, rather than just direct value use.

**Comment by azreika** [comment]
Another related problem. The following program is translated incorrectly:

```
.decl A(x:number, y:number)
.output A

A(x,y) :- x = range(1,3), y = range(1,3), x + y = 3.
```

to:

```
.decl A(x:number, y:number) 
A(range(1,3),range(1,3)) :- 
   (range(1,3)+range(1,3)) = 3.
```

at the end of the AST pipeline. These are all independent ranges here. As a result, seems like even if the RAM was fixed to treat separate RAMs independently, the wrong result might still be generated here. The program seems like it will output all tuples (1,1), (1,2), (2,1), (2,2), when in reality only (1,2) and (2,1) should be output. Should keep this in mind when resolving.

**Comment by azreika** [comment]
First problem is because generators (aggregators and multi-result functors) are treated as the same if their AST counterparts are syntactically equal. To fix this, a different identification mechanism should be used - such as the address of the argument, or a special ID. Aggregators and other single-result generators can be treated as a special case for efficiency so that multiple generators aren't created.

This will solve the first issue, but solves neither the AST issue (too many results generated) nor the provenance issue (souffle crash).

**Comment by ohamel-softwaresecure** [comment]
We have a few hacks in our fork to make this work.
1) early transform that hoists & binds every generatives (functors and aggregates, which are not always pure in our fork) to a fresh variable
2) modified alias-resolver to avoid unifying variables which are equal-constrained with a generative RHS
3) basically the same fix as #1677, except we pessimistically avoid CSE-ing aggregates. this isn't a huge problem because the alias resolver doesn't duplicate aggregates any more due to 1 and 2.

Apologies for not fixing these earlier in a PR, our fork has speciated due to the number of changes and I haven't had the time to upstream some of these changed.

**Comment by ohamel-softwaresecure** [comment]
Ideally souffle would allow intrinsic atoms, and not just intrinsic functors. That would allow you to do things like `!range(lo, hi, step, _)`, which is currently impossible. We've a draft impl on our fork but haven't finished shaking out the bugs.

**Comment by azreika** [comment]
Thanks for the notes! The first three points match up with plans, so that's nice.

Point 4, I did not expect. I would have expected the RAM to correctly reorder this since `j` would have to be grounded before use. Thanks for bringing this up! 

I agree with the idea of intrinsic atoms - the range operator works very naturally as an atom, since we're instantiating multiple values based on certain parameters.

**Comment by azreika** [comment]
PR #1677 is merged in, fixing the initial bug. Focus should now be on (1) supporting ranges in provenance, and (2) fixing bug 2, namely:

```
.decl a(X:number, Y:number, Z:number)
.output a()
a(X,Y) :- X = range(0,3), Y = range(0,3), X < Y, X + Y = 3.
```

should produce only the tuple (1,2), but currently produces every combination (X,Y) in [0,2] x [0,2] because of incorrect alias resolution.

**Comment by azreika** [comment]
Waiting on PR #1387 (broad ast2ram refactoring) before moving on with this, as the changes will overlap.

**Comment by azreika** [comment]
The second bug mentioned above has been fixed. Fixing the bug where the value of one range is used in another, as in `a(x) :- j = range(0, 3), x = range(0, j).`, should probably be fixed next.

**Comment by azreika** [comment]
Prioritising issue #1705 since this may change how the information is accessed, and likely make things cleaner.

**Comment by azreika** [comment]
With the major refactoring of the translator structure complete, correct range scheduling should now be looked into.

**Comment by b-scholz** [comment]
This has been fixed by the refactoring. The output of the example is the following:
``
---------------
A
x	y
===============
1	1
1	2
2	1
2	2
===============
```
and the RAM representation is
```
PROGRAM
 DECLARATION
  A(x:i:number,y:i:number) 
 END DECLARATION
 SUBROUTINE stratum_0
  BEGIN_DEBUG "A(@generator_0,@generator_1) :- \n   @generator_0 = range(1,3),\n   @generator_1 = range(1,3).\nin file /Users/bernhard/Projects/souffle/src/tt.dl [4:1-4:42]"
   QUERY
    RANGE(number(1),number(3)) INTO t0
     IF (t0.0 = t0.0)
      RANGE(number(1),number(3)) INTO t1
       IF (t1.0 = t1.0)
        INSERT (t0.0, t1.0) INTO A
  END_DEBUG
  IO A (IO="stdout",attributeNames="x\ty",auxArity="0",headers="true",name="A",operation="output",params="{\"records\": {}, \"relation\": {\"arity\": 2, \"params\": [\"x\", \"y\"]}}",types="{\"ADTs\": {}, \"records\": {}, \"relation\": {\"arity\": 2, \"types\": [\"i:number\", \"i:number\"]}}")
 END SUBROUTINE
 BEGIN MAIN
  CALL stratum_0
 END MAIN
END PROGRAM
```
