### ISSUE TITLE
what does ”@info" in a realtion mean? What kind of realtion doesn't have this attribute?

### ISSUE THREAD

**Issue by qunqunqun** [souffle-lang/souffle#1730]
I'm interesting in souffle's provenance. However, I get some problem while reading source code. By using provenance, I wanna get information of all clause in dl with rule number. For example, A.dl

A(x) :- B(x)
A(x+1) : B(x), C(x)

And I wanna get:
**A - R1 - B
A - R2 - B
A - R2 - C**
**likes add extra info to predecence graph. So I wanna ask what kind of relation does not have "@info" ?**
 
**For example in ExplainProvenanceImpl.h**

            // only process info relations
            if (name.find("@info") == std::string::npos) {
                continue;
            }

**Comment by taipan-snake** [comment]
Hello, good question! The `@info` relations store some meta-information about the clauses in the program. This is necessary for the ExplainProvenance system because Souffle doesn't expose this meta-information directly from the C++ interface, so we store it in the form of an `@info` relation instead. For example, if there is a clause like 
```
path(x, z) :- edge(x, y), path(y, z).
```
then an `@info` relation is generated with a single fact:
```
path.@info.2(2,"x,z","edge,x,y","path,y,z","path(x,z) :- 
   edge(x,y),
   path(y,z).

   .plan 0:(2,1)").
```

This tells us that this rule 2 of the `path` relation, it has 2 body atoms, the head atom contains variables `x` and `z`, the first body atom is `edge(x,y)`, and the second body atom is `path(y, z)`. There is also a text representation of the clause itself. These info relations are processed in ExplainProvenance, where it uses this meta-information to generate the proof trees.

As for your question, it may be possible to process these `@info` relations to give the information you need. Let me know if you need some more help!

**Comment by azreika** [comment]
Feel free to reopen the issue if you need more help!
