### ISSUE TITLE
ast2ram/ValueTranslator.cpp:52: Assertion `index.isDefined(var) && "variable not grounded"' failed.

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1796]
Hi guys,
Consider the program: 
```
.decl K(A:symbol)
.decl C(A:symbol)
.decl g(A:symbol, B:symbol) inline
.decl z(A:symbol)

.decl out(A:symbol)

K("2pp0k").
C("sVaHE").

g(p,cat(d,p)) :- K(p), d=substr("QVf",0,1).
z(v) :- C(v), contains("X",v).
out(D) :- z(D), g(D,D).
.output out
```

With `--magic-transform=*`, I get  the following:
```
$ souffle -w --magic-transform=* bug.dl
souffle: ast2ram/ValueTranslator.cpp:52: virtual souffle::Own<souffle::ram::Expression> souffle::ast2ram::ValueTranslator::visitVariable(const souffle::ast::Variable&): Assertion `index.isDefined(var) && "variable not grounded"' failed.
Aborted
```

Souffle version: 0b1b282943419263dd8eb331bfe05bc48db38efb

**Comment by azreika** [comment]
This problem only seems to arise when inlining and magic-set are used together on this program.

Here's a more minimal program with the same problem:

```
.decl a(X:number)
.decl b(X:number, Y:number) inline
.decl c(X:number)

.decl out(X:number)

a(0).

c(x) :- a(x), x != 0.
out(x) :- c(x), b(x,x).

.output out()
```

If inline is removed, or magic-set is not toggled, the program runs normally.

**Comment by azreika** [comment]
The following program fails with magic-set:

```
.decl a(X:number)
a(0).

.decl b(X:number)
b(x) :- a(x), x != 0.

.decl out(X:number)
out(x) :- b(x), a(x), x+1 = x.
.output out()
```

being transformed into:

```
.decl a(X:number) 
.decl out(X:number) 
.decl b.{b}(X:number) 
.decl @magic.b.{b}(X:number) 
a(0).

out(x) :- 
   b.{b}(x),
   a(x),
   (x+1) = x.

b.{b}(x) :- 
   @magic.b.{b}(x),
   a(x),
   x != 0.

@magic.b.{b}(x) :- 
   (x+1) = x.
```

`x` is obviously not grounded in that final rule for `@magic.b{b}`. This seems like a problem in determining whether variables are bound when the 'definition point' depends on itself. Logic should be fixed in `ast/utility/BindingStore.cpp`.

**Comment by TomasPuverle** [comment]
Hi @azreika,

I am looking at magic sets for the first time and I think I see what you mean.  However, what's the correct answer here?  It seems the preceding transforms has generated an invalid clause.  What's the desired solution/semantics?  Have it always fail?  (If that's the case, we would have to revisit this logic when discussing floats because +-Inf would definitely satisfy that clause, right?)

Thanks,

Tom

Thanks,

Tom

**Comment by azreika** [comment]
Once the binding store problem is fixed (i.e. correctly deciding which variables are bound), then magic-set should work again, provided no other bugs exist. Magic-set uses the binding information to create the appropriate clauses, and so would not produce invalid clauses like this in the presence of correct binding information.

**Comment by b-scholz** [comment]
This bug disappeared with the latest inline bug fixes.
