### ISSUE TITLE
clause->head is null?

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1813]
After my discussion in PR #1810, I decided to see what it would look like if I refactored the code to pass around vectors of references (e.g. from getChildNodes) rather than vectors of pointers to better express the invariants that "this can't be nullptr".  I'm only doing this in the "ast" portion right now not to cause merge issues with the ram work they are doing.  Eventually, I would like to push this to all the accessors, and propagate constness.

However, I am running into an issue when clause->head is nullptr.  Is this a bug or an actual possibility in the code?  What does the invariant express?

If this is a real possibility, are there any other such eventualities that you can think of?

**Comment by mmcgr** [comment]
I'm not sure if it's your current issue, but the ast has the problem of dealing with incomplete elements during parsing. Sometimes elements of the ast are not valid until the datalog is fully processed, even when the datalog is valid. This is expressible with nullptr, but harder to do with references. This may also affect constness.

**Comment by TomasPuverle** [comment]
Thanks.  I encountered the issue while trying to change `ast::Node::getChildren` to return references instead of pointers.  It turns out that sometimes `head` is not set; at present, the head could be not set but the nullptr is still added to the list of children in as the first step of `ast::Clause::getChildNodes`.  This is guarded against in the visitor (it skips recursion in child node is nullptr; however, this strikes me as not ideal.

Hence my question: Unless the head being nullptr is a valid invariant of the clause (but I don't think so), the invalid state should be inexpressible.  In any case, I can see the few places where clauses are being constructed and I understand your point.

There are a few other places where clause->head is being checked for nullptr, but again, if this is not a desirable state, I would prefer to remove these in order not to "obscure" the logic.

(This is related to the work I'm doing, starting with #1814.)

**Comment by azreika** [comment]
Certain invalid states might exist because the product from parsing (the representation prior to the semantic checker) uses the same internal representation as the AST object we manipulate. After the semantic checker, these invalid states should preferably not be possible. Separating these contexts fully might involve introducing a new IR.

If it is not possible through parsing, (if it's set later, for example), then clause heads should never be nullptr.

**Comment by TomasPuverle** [comment]
@azreika - This is fixed in one of my recent PRs, thanks.

**Comment by b-scholz** [comment]
In the past, we had discussions whether we should have an IR for parsing and a high-level IR for semantic transformations.

We decided against having two IRs so far because we had to focus on more pressing issues. 

In future, that might be a good idea to replicate the IR. However, there are costs involved keeping two IRs in sync, etc.

At the moment there are more important issues to resolve such as the parser-driver performs semantic transformations for disjunctions / negations of sub-clauses #1409. I hear that @ohamel-softwaresecure has been working on this.

**Comment by TomasPuverle** [comment]
That makes sense, and my recent PR mentioned in this issue fixes this for now.  
Also, as I alluded to in another comment, it's likely C++23 will get support for true functional-style pattern matching like Haskell/ML etc, which could very well be the answer you are looking for: https://wg21.link/P1371, section 4.5.
