### ISSUE TITLE
ast/transform/MaterializeAggregationQueries.cpp:309: Assertion `!curArgType.empty() && "unexpected empty typeset"' failed.

### ISSUE THREAD

**Issue by rhendrix42** [souffle-lang/souffle#1832]
Hi guys,
Consider the following program: 

```
.decl R (x:number, y:number)  brie
.decl A (x:number, y:number, z:number)  btree
.decl AKYP(a:number)
.decl UTUA(a:number) btree
.decl THGW(a:number, b:number)
.decl EOXG(a:number)
.decl DBCZ(a:number, b:number, c:number) btree
.decl SYPN(a:number, b:number)
.decl ZZGY(a:number, b:number) btree
.decl ZOLF(a:number) brie
.decl SOCN(a:number) btree
.decl NEGATED(a:number) btree

R(1,2).
R(2,3).
R(3,5).


THGW(y,min(d,y)), UTUA(d):- A (nrc,d,y), R (y,d), !A (nrc,d,_), d = max MDA : { A (Xwl,MDA,Xwl), Xwl = to_number("5")}.
EOXG(z), UTUA(pcv) :- THGW(zgu,pcv), THGW(pcv,z), ord(z) != ord(zgu), z =  sum avR : { A(GTL,GTL,avR), ord(GTL) >= ord(GTL)}. 
DBCZ(e,l,o) :- R(l,o), THGW(rgo,e). 
ZZGY(m,j) :- R(j,m), UTUA(ysf). 
ZOLF(x) :- R(whm,x), SYPN(x,fao). 
NEGATED(ywi) :- UTUA(ywi), THGW(ywi,y), !UTUA(ywi).
SOCN(y) :- UTUA(ywi), THGW(ywi,y), !NEGATED(ywi).    
```

```
$ ./souffle rules.dl 
souffle: ast/transform/MaterializeAggregationQueries.cpp:309: souffle::ast::transform::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(souffle::ast::TranslationUnit&)::<lambda(souffle::ast::Clause&)>::<lambda(souffle::ast::Aggregator&)>: Assertion `!curArgType.empty() && "unexpected empty typeset"' failed.
Aborted
```

Souffle version: bcb2a08e58725baf87f7c4a5e90e9358212de00a

**Comment by TomasPuverle** [comment]
This could be a bug in "MaterializeSingletonAggregation" (surprisingly).  

See the attached output of `src/souffle bug/bug.dl -D- --debug-report=bug/crash.html` - you will see that MaterializeSingletonAggregation is the last transformer run.

If I disable that transformer, using `src/souffle bug/bug.dl -D- --debug-report=bug/crash-no-single.html --disable-transformers=MaterializeSingletonAggregation`, the run succeeds and is the second attached debug output.

[crash.txt](https://github.com/souffle-lang/souffle/files/5826946/crash.txt)
[crash-no-single.txt](https://github.com/souffle-lang/souffle/files/5826947/crash-no-single.txt)

(Note that you will need to rename the *.txt files to *.html, since GitHub won't let me upload files with .html extensions)

The root of the problem is that inside of the `__agg_single` clauses generated, the MaterializeAggregateQueries transformer is trying to figure out the types of the new synthetic clauses and it's failing to get the type back from the type inferencer.  Part of the question I have for the @b-scholz's team is whether AggregateSingletonQueries should even apply in this case, but that could just be an optimization.

**Comment by b-scholz** [comment]
I cannot make it crash with the latest version of Souffle. I need to further investigate. I run this program on a Mac OS X system.

**Comment by b-scholz** [comment]
Note that the aggregate transformation should not produce an auxiliary relation since the aggregate is simple. This is wrong.

We haven't attempted to tidy up aggregates yet - we were busy with the AST and AST-to-RAM Translator refactoring. 

There are several bugs related to aggregates in the system, which we should fix next.

**Comment by rhendrix42** [comment]
Interesting. I am still able to reproduce this on the latest version of Souffle (9caed2239e3f8c921acec8eddcb5c01c8be5431)
on my machine:
**Operating System**: Debian GNU/Linux 10 (buster)
**Kernel**: Linux 4.19.75.1.amd64-smp
**Architecture**: x86-64
