### ISSUE TITLE
-fwrapv?

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1836]
Why is the souffle code compiled with "-fwrapv"?  I understand the flag but I'm curious as to why it was introduced/why it's needed.

**Comment by b-scholz** [comment]
In the early days (before we had signed/unsigned/float as primitive types), there was a lot of confusion whether our numbers are signed or unsigned. In the light of the new type system, we should review this.

**Comment by ohamel-softwaresecure** [comment]
This actually has to do with the following:
1) Clang UB sanitizers get very upset about overflows, and the test suite deliberately triggers these. i.e. signed wrapping is part of souffle's semantics, as evidenced by the fact that there are test cases doing that.
2) Synthesis emits C++ code. Add in various optimizations & transforms to your datalog program that does int overflow -> you get a C++ file that manifests provable signed overflow. Interpreter mode might run "as expected" (but that's not mandated either), but the synth'd version is screwed because the compiler is now legally allowed to wipe your drives and fill them with copies of NetHack or Caves of Qud.
3) Interpreter/synth does a *lot* of bit-reinterp bashing to pipe primitive values around. These should all be done now via `ramBitCast` to prevent issues, but before it was pretty wild.

**Comment by TomasPuverle** [comment]
@ohamel-softwaresecure Thanks for the detailed explanation!  That makes sense to me.
