### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by brianfairservice** [souffle-lang/souffle#1837]
I would like a [conan](https://conan.io/) package for souffle.  I can implement a CI job which would build and upload the package to conan center, and make a pull request if its something you would considering accepting.  I see you are considering [switching from travis CI](https://github.com/souffle-lang/souffle/issues/1754) and may not want to complicate things at the moment.  Let me know if I should take the time.

**Comment by brianfairservice** [comment]
Nevermind, I see now that the way to build conan packages and upload them to conan center is to instead make a PR on https://github.com/conan-io/conan-center-index.  Closing this.

**Comment by b-scholz** [comment]
Is there a way to use GITHUB Action and other systems?

Unfortunately, we don't have free capacity for building a new testing infrastructure. 

At the moment, we use our Sydney Uni servers for continuous testing. 

Ideally, we have a system in place so that everybody can have continuous testing running on their private repos (like what we had for travis-ci). 

I really don't have a solution for this problem at the moment.
