### ISSUE TITLE
macOS brew installation does not support concurrent jobs

### ISSUE THREAD

**Issue by MrToph** [souffle-lang/souffle#1839]
Hi,

I installed souffle on my Mac through brew as mentioned [in the docs](https://souffle-lang.github.io/install).
When I run `souffle --jobs auto` it fails with this error:

```
This installation of Souffle does not support concurrent jobs.
```

This seems to be related to OpenMP which is mentioned in the `Build` section.

> OpenMP is not required, but does improve runtime for large programs. Testing with multiple threads will also fail if OpenMP is not installed.

Is there a way to get concurrent job support without building souffle myself?

**Comment by XiaowenHu96** [comment]
Hi there,
I'm not familiar with the Brew formula, maybe @mmcgr can answer that.
But as far as I know, building Souffle on MacOs is not very hard.
In order to have OpenMP supported, you have to use gcc as the compiler - (last time I checked, clang does have OpenMP supported, but requires link to LLVM lib and I never tested it) 

Then you just execute the command at the root dir: `sh ./bootstrap && CXX=gcc ./configure && make`.

**Comment by b-scholz** [comment]
The standard clang installation on Mac OS X (by apple) has OpenMP not enabled and hence you cannot use -j <nr> out of the box. 

An easy workaround is to install gcc via brew and use gcc instead of clang. There should be some notes on the doc page related to this issue.

**Comment by MrToph** [comment]
Ok, thanks. I was looking for a solution that doesn't require a custom compilation but as the compilation seems straight forward I'll just do that
