### ISSUE TITLE
R/X-trees for indices?

### ISSUE THREAD

**Issue by TomasPuverle** [souffle-lang/souffle#1851]
I was thinking about indexing support in souffle and the need to quickly select subsets of clauses/facts.  At the moment, my understanding from reading the code is that souffle uses B-trees (or B-tries) to store result tuples.  However, the structure of tuples in those datastructures is still "one-dimensional" and doesn't support indexing across the "dimensions" of the individual tuples.

R-trees (and specifically [R*-trees](https://en.wikipedia.org/wiki/R*_tree)) are essentially a high-dimensional generalization of B-trees, and in comparison to some of the "better known" algorithms like k-D trees, they support efficient updates and don't degenerate for high-dimensional data (n >= 3).  

Most importantly, they also allow e.g. rectangular" queries.  For example, in 2-D one can say things like "select all s.t. (10 <= x <= 20, *)" or "(10, *)".  This appears to me, at first sight, as highly desirable and is somewhat reminiscent of some of the other optimizations souffle tries to do (e.g. the MagicSet).
R*-trees can be updated, and also have fast bulk-loading algorithms for data known ahead of time.  Somewhat interestingly, R-trees also support "proximity" queries.  While I don't see that as essential, it might be an interesting idea to explore in terms of "find a tuple closest to the one I'm asking for", based on some norm.

I did a few basic google searches but have not found anything referencing "R trees" and "datalog".  Is this something that has been considered and rejected before?

I should also mention that there is another datastructure called an X-tree, which is effectively the N-dimensional generalization of the brie (as far as I can tell from reading the brie code).  It's basically a trie which uses the bits of the stored numbers to create a high-dimensional query-able datastructure.  It happens to work very well with integer values; given that internally souffle represents everything as a RamDomain int, it might have some applications.

**Comment by b-scholz** [comment]
Sam just finished his Honours Thesis 

https://souffle-lang.github.io/pdf/samthesis.pdf

In his thesis, Sam investigated whether R-Trees are a suitable option for Souffle. 

Initially, R-Trees looked very promising (we used Boost's R-Trees) but unfortunately they are not as fast as B-Trees.  Each node has to carry a bounding-box and placing elements in an R-Tree has all sorts of issues. 

The bottom-line is that R-Trees cannot give any reasonable worst-case execution bounds for a primitive search.  In contrast, a primitive search can be executed in the size of its output (omitting log-terms now) when implemented in B-Trees.

If not all primitive searches are necessary or in special situations, it is faster / better to have a cluster of B-Trees. That is the bottom-line of @SamArch27 thesis. He may comment on this as well.

**Comment by TomasPuverle** [comment]
Oh, this is awesome!  I will read the thesis in more detail, looks interesting.  What a coincidence that my question can be answered so thoroughly.  Thanks @SamArch27.

**Comment by SamArch27** [comment]
@TomasPuverle 

There are also a set of slides which are easier to understand than the thesis: 

https://souffle-lang.github.io/pdf/sampres.pdf 

It would be simple to build an R-Tree index for every relation without using any information about which search operations are performed on each relation. However, since Soufflé can inspect the search operations on relations during the compilation process, it can leverage this information and specialize B-Tree indexes to efficiently evaluate these searches, emitting them during the code generation phase.

R-Tree Index:
+ You only need a single index to cover every search operation on a relation.
- It takes O(n) where n is the size of a relation to perform a search.

B-Tree Index:
- Multiple B-Tree indexes may be required to cover every search operation on a relation, and each B-Tree index must be maintained during evaluation time.
+ It takes O(log(n) + |Q|) in amortized time complexity where Q is the set of tuples satisfying the search operation (i.e. the output of the search) to perform a search. 

The last point is crucial. In applications of Soufflé, we have seen extremely large relations, i.e. giga-scale (billion tuple+). Yet, the size of the output of searching these relations is very small. B-Tree indexes guarantee the search complexity to be proportional to the size of the output. R-Tree indexes have no such guarantee. Searching them could require scanning nearly all of the tuples in the relation, resulting in an explosion in evaluation time, particularly in multi-way joins.

The key insight is that B-Tree indexes can cover multiple search operations on a relation so we do not need to naively cover each search operation with its own B-Tree. We can instead compute a minimum index selection of B-Tree indexes to cover every search for a relation by solving a minimum chain covering problem over an associated lattice in polynomial time.

The advantage is that we minimize the maintenance cost during evaluation time since we have minimized the number of B-Tree indexes. Additionally, we ensure that every search operation is evaluated quickly because a B-Tree index covers it.

My contribution was to extend this automatic index selection framework to support indexed inequalities.

Experimentally, I compared the cluster of B-Trees with the Boost R-Tree index and found the performance to be dramatically slower (>1000x slower). For my thesis, even when using R-Tree indexes only for relations with inequalities, we still observed it to be still much slower (up to 143x slower).

The thesis points to a branch on my fork of Soufflé where I did the evaluation. For benchmarks, the key one is a binary disassembler, DDISASM which is open-source and can be found here:

https://github.com/GrammaTech/ddisasm

In the past, when the technique was being developed, alternative approaches were considered, such as the use of hash indexes, but those were found to not be competitive compared to B-Tree indexes. 

http://www.vldb.org/pvldb/vol12/p141-subotic.pdf

Ultimately, it's a matter of inspecting the Datalog program and it's search operations during compile time and using this information to specialize indexes which guarantee strong complexity bounds on each search.

Let me know if you have any further questions!

**Comment by TomasPuverle** [comment]
Wow @SamArch27,

Thank you for such a great summary of your work.  Other than the algorithmic upper bounds, it make perfect sense that B-trees could outperform R-Trees because you know something about the data up front!  That is a great insight and hopefully will help me with understanding your thesis.  Is your work part of the souffle codebase yet?

As an aside, I'm curious to try to run souffle on some larger problems - it's hard to try to understand the performance implications of one's designs without being able to run some real-world benchmarks.  I'll check out ddiasm at some point but if you happen to be aware of any other examples/performance tests which are reasonably easy to run, please let me know!

**Comment by SamArch27** [comment]
@TomasPuverle 

My work for indexed inequalities has been merged to master.

If you're interested in the code you can find it in:

src/ram/analysis/Index.h
src/ram/analysis/Index.cpp

There are a number of applications of Souffle such as:

DOOP (Static Program Analysis of Java Programs):

http://doop.program-analysis.org

Gigahorse (Decompilation of Smart Contracts):

Source: https://github.com/nevillegrech/gigahorse-toolchain 
Benchmarks: https://github.com/nevillegrech/gigahorse-benchmarks

There are more applications that @b-scholz can tell you about. 

It's most helpful in my experience to use the built-in profiler to understand where the time is being spent during evaluation.

**Comment by b-scholz** [comment]
We should setup a benchmark suite for Souffle that contains a wide range of applications.
We have a small benchmark suite to check the performance as part of the continuous integration:
http://plang1.it.usyd.edu.au/jenkins/job/Master-Performance/plot/

However, that should be improved with larger benchmarks. 

As mention by Sam, good candidates are DOOP and Gigahorse but also DDISASM (GrammaTech), Amazon's VPC benchmark, and various other benchmarks related to smart contract analysis.
