### ISSUE TITLE
Possible bug in record grounding

### ISSUE THREAD

**Issue by markusscherer** [souffle-lang/souffle#1865]
Hi!

I just came across the following behavior that I don't really understand:

Consider we want to model a Stack of numbers with records and have a rule that increases the top element by one. One way I assumed to be valid was the following one:

```souffle
.type Stack = [value: number, rest: Stack]

.decl A(S: Stack) 
.decl B(S: Stack) 

.output B

A([2, nil]).

B(pushed) :-
  A(S),
  [_, popped] = S,
  [peek, _] = S,
  pushed = [peek+1, popped]
  .
```

Unfortunately, this results (in the most current commit `4aea4a3` as well as in the version of souffle I was using so far) in a compilation error:

```
Error: Ungrounded record in file record-grounding-clean.dl at line 14
  pushed = [peek+1, popped]
-----------^--------------
1 errors generated, evaluation aborted
```

The more natural variant of this rule works as expected, but is in our setup (generating souffle code from a specification written in an another language) more difficult to implement:

```souffle
B(pushed) :-
  A(S),
  [peek, popped] = S,
  pushed = [peek+1, popped]
  .
```

The most surprising thing for me was, that replacing the wildcards `_` with singleton variables (`_a`, `_b`) makes the code work:

```
B(pushed) :-
  A(S),
  [_a, popped] = S,
  [peek, _b] = S,
  pushed = [peek+1, popped]
  .
```

is this behavior intended?

**Comment by b-scholz** [comment]
We have here a Datalog language, and we must have notions of grounded Variables. I.e., we cannot have free variables that are not bound to elements in a tuple of a relation.  In your example,  you are using an extension of Souffle that is not so well documented. It relies on equivalence and substitution. 

For example, the program.
```
B([x,y]) :- 
 A([x,y]). 
```
has variables `x` and `y`, which are grounded. They show up in atoms in the body of a rule.

In the following program, 
```
B(S) :- 
  A(S), S = [x,y]. 
```
the variables `x` and `y` are ungrounded because they show up in a constraint rather than an atom's argument. Note that the variable `S` is grounded. 

However, souffle does internally a substitution, and it will become 
```
B([x,y]) :- A([x,y])
```

You can check this by typing,
```
 souffle <example> --show=transformed-datalog
```

In your example, the correct way to write it (without relying on Souffle's substitution feature, which may or may not work) is, 
```
 B([peek+1, popped]) :- 
    A([peek, popped]).
```

**Comment by markusscherer** [comment]
Thanks for the detailed response! I wrongly assumed that constraining variables to grounded or constant terms would _always_ ground them. Is the substitution implemented in `src/ast/transform/ResolveAliases.cpp`?

**Comment by b-scholz** [comment]
That is correct. RemoveAliases performs this and your example would be an example of how we could improve the alias transformation in the presence of records / ADTs.

**Comment by b-scholz** [comment]
This might be a smaller case for improving the alias transformer:
```
B(S) :-
  A(S),
  [x, _] = S,
  [_, y] = S,
```
This is quite a special case because we have for variable S two terms. 
Normally, the resolution principle would say, choose one term and substitute, i.e., we would obtain
```
B([x,_]) :-
  A([x,_]),
  [_, y] = [x,_]. 
```
However, this leads to ungrounded variables and the transformation is semantically wrong. 

To overcome this, we would need to make unnamed variables named ones. 
```
B(S) :-
  A(S),
  [x, t1] = S,
  [t2, y] = S,
```
would be transformed to:
```
B(S) :-
  A(S),
  [x, t1] = S,
  [t2, y] = S,
```
and followed by the substitution:
```
B([x, t1]) :-
  A([x, t1]),
  [t2, y] = [x, t1].
```

**Comment by b-scholz** [comment]
However, this leads to other issues related to the semantics of record initialiser and their grounding semantics, etc.

**Comment by markusscherer** [comment]
Thanks again for the detailed response! I was able to rewrite our code generation in a manner that does not rely on the inlining of aliases.

**Comment by b-scholz** [comment]
Great!
