### ISSUE TITLE
Allow user to specify there files should be generated

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#188]
Currently many files are generated in souffle and in particular the souffle interface. It would be nice if the user could specify where these files live.

**Comment by seanmcl** [comment]
+1

**Comment by b-scholz** [comment]
There is the plan to improve the I/O system of Soufflé. Instead of having relation qualifiers that control the input / ouput (e.g. input/output/printsize), we would like to introduce an input/output directive that governs the input/output facilities of Soufflé. The system is expanding in its interface capabilities and we would need input / output directives that can cope with 
- text files  
- compressed text files 
- sqlite3 database 
- programmatic C++ interfaces (JNI interface / C++ OO interface)

**Comment by b-scholz** [comment]
Martin has implemented a new interface for test/sql/compressed text. 
The JNI interface needs to be adapted.
