### ISSUE TITLE
Auto index off flag

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#189]
Although auto index is used by default and it pretty much always results in an improvement we should allow a flag to turn it off - for research purposed at the very least.

**Comment by psubotic** [comment]
Hi @HerbertJordan , can you when you have time integrate a no auto index no index flag? so that auto index is default.

**Comment by HerbertJordan** [comment]
I have this running within my own branch. I can submit a merge request.

**Comment by HerbertJordan** [comment]
The pull request has been submitted.

Since those are features not supposed for the general user, I did not include them into the command line interface. Instead I am utilizing environment variables to control this behavior.

To disable the auto-index support, define the environment variable SOUFFLE_USE_NAIVE_INDEX before running souffle (you will see a warning that auto-index is disabled to verify the effect). For disabling the index supported range queries at all, define SOUFFLE_USE_NO_INDEX within your environment variables. The value you assign to those variables is not important. The features will be disabled whenever those variables are defined.

**Comment by psubotic** [comment]
Great, Many thanks!
