### ISSUE TITLE
Question: Should --show=transformed-datalog output valid Souffle code?

### ISSUE THREAD

**Issue by langston-barrett** [souffle-lang/souffle#1926]
I just attempted to feed Souffle the output of `--show=transformed-datalog` (for the sake of convenience, since it makes one big file out of my many-file program), and got this error:
```
Error: syntax error, unexpected ., expecting end of file in file test.dl at line 158
.type unification.AllocWithContext = [?aCtx:Context, ?alloc:Allocation]
-----------------^------------------------------------------------------
```
The error comes from a type defined inside a component:
```
.comp UnificationPointsTo : PointsTo {
  // snip
  .type AllocWithContext = [?aCtx: Context, ?alloc: Allocation]
```
I only ask whether this is expected to work because this appears to be the *only* error in my fairly large program, so it seems it's not far off.

**Comment by b-scholz** [comment]
Yes - that is expected. We made the output as close as possible to the actual input language. 

The type qualification is not parseable/scannable and needs to be replaced by _ or something like this.

We could change this in future so that generated simple Datalog can be directly parsed. Mind you, that this functionality was created for debug purposes only.

**Comment by langston-barrett** [comment]
> We could change this in future so that generated simple Datalog can be directly parsed. Mind you, that this functionality was created for debug purposes only.

Gotcha, so it sounds like it's not currently the expectation that it can be re-parsed, but it could probably be made so with not too much effort. This isn't a big deal to me, I was just wondering.
