### ISSUE TITLE
Incorrect inline result

### ISSUE THREAD

**Issue by zhu-he** [souffle-lang/souffle#1956]
The following datalog output incorrect result:
```
.decl a(x: number, y: number) inline
.decl b(x: number, y: number)
.decl c(x: number, y: number)
a(x, y) :- x = y.
c(x, y) :- b(x, y), !a(x, y).
.input b
.output c
```
Input b.facts
```
1	1
1	2
2	1
2	2
```
and output empty c.csv.

**Comment by b-scholz** [comment]
The result is correct because there is no rule for relation `b` nor there is an input statement. Hence, the relation `b` is empty and the result of `c` is empty. I hope that helps.

**Comment by zhu-he** [comment]
> The result is correct because there is no rule for relation `b` nor there is an input statement. Hence, the relation `b` is empty and the result of `c` is empty. I hope that helps.

Relation `b` is input from file `b.facts`.

If the negation `!` is removed, the output `c.csv` gives the correct result:

```
1	1
2	2
```

**Comment by b-scholz** [comment]
Oh - I see. I did not see the fact file. 

The problem is that the rule `a(x,y) :- x = y` is an ungrounded rule. Technically, it is not permitted. The semantic checker should throw an error. The problem is that variables `x` and `y` cannot draw values from a domain. 

The semantic checker should report an error (i.e. the program is illicit).

You would need to rewrite the rule as follows:
```
.decl a(x: number, y: number) 
.decl b(x: number, y: number)
.decl c(x: number, y: number)
a(x, y) :- x = y, b(x,y). 
c(x, y) :- b(x, y), !a(x, y).
.input b
.output c
```

**Comment by b-scholz** [comment]
The semantic checker should report this as an error and not let the program pass.

**Comment by b-scholz** [comment]
The problem is related how inlining is performed; there is a variable binding constraint `a(x,y) :- true` after the inline transformation that is not considered.
