### ISSUE TITLE
CI tuning vs Github Actions VM runners ?

### ISSUE THREAD

**Issue by quentin** [souffle-lang/souffle#1985]
Hi, I noticed that the CI scripts are running the test phase with `-j6` but the Github VM runners have only 2 cpus and 7GB of RAM.

Considering the case when OpenMP is detected, each test will:
- run souffle to compile the datalog.
- fork 8 threads to evaluate/run the program.

That's potentially 48 concurrent threads. Or 6 gcc compilers that may use ~1GB of memory each.
Is it a concern that race-conditions bugs are less likely to be exercised and processes might be killed due to lack of memory?

**Comment by b-scholz** [comment]
That is a great observation; we will look into this issue.

**Comment by b-scholz** [comment]
We noticed in the past that large numbers of jobs increase memory consumption substantially.

**Comment by b-scholz** [comment]
Let's choose the appropriate number of threads by OpenMP using the flat `-j` without the number of threads. That might be safer.

**Comment by XiaowenHu96** [comment]
We used to use self-host machines and forgot to change it when switching to VMs from Github. 
Let's see if `-j` is better

**Comment by XiaowenHu96** [comment]
I'm wondering if we should change the parallel tests themselves to be run with `-j` or just `-j8`. 
We probably should add an extra option in CMake so that we can configure it on need.
Also, automake is retiring soon so no need to fix those I believe.

**Comment by quentin** [comment]
I would use `-j8` or less for Souffle and `-j2` for CMake/CTest. So that only 2 tests runs at the same time.

**Comment by quentin** [comment]
Even the number of jobs during the build may be decreased to `-j2` or `-j3` knowing that the VMs have only 2 cpus and compilation is computation intensive.

**Comment by quentin** [comment]
Sorry for the noise, should we also add a CI matrix entry where openmp is disabled ?

**Comment by b-scholz** [comment]
Hmm - that is a good suggestion. However, I feel that the MacOSX test does cover a build and a test without OpenMP.

The reason is that the standard C++ compiler of MAC OS X is always built without OpenMP. If we want to be extra cautious, we could add this configuration for the Linux box, but the test time will increase approximately by 1 1/2 h.

**Comment by quentin** [comment]
The `clang` compiler of MAC OS X does not support OpenMP by default.
But in the CI the selected compiler for `OSX` job is `g++` and it supports OpenMP:
```
checking for g++-10 -std=c++17 option to support OpenMP... -fopenmp
```

**Comment by b-scholz** [comment]
Oh - that is a good point.

**Comment by b-scholz** [comment]
I give up. Building Souffle with the standard MAC OS X compiler is too hard. It seems that the main problem is that the standard include directories do not work properly. We would need to set `CXX=/usr/bin/c++`; otherwise, the c++ in the Developer Tool path is picked up, and the compilation process falls apart.

I think it is easier to have a new Linux box for which we disable OpenMP.

**Comment by quentin** [comment]
Hi,
The CMake now have a `SOUFFLE_USE_OPENMP` switch that could be used to create a new flavor in the CI:
https://github.com/souffle-lang/souffle/blob/94c7e647c994a875ba3dfe7a3a2177579065eec7/CMakeLists.txt#L99

**Comment by b-scholz** [comment]
Would you like to create one test for this?
