### ISSUE TITLE
Give configure --enable-xxx or disbable-xxx options to not require some libraries

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#199]
Some uses of souffle do not require some dependencies. For example:
- If using souffle as a library no need for boost
- if _not_ using the jni interface no need for jni
- if not using the sql stuff no need for sqlite3

If someone who is cool with automake and libtools has time that would be awesome. I am attack this in Dec otherwise.

**Comment by icesparrow** [comment]
I can do that. I was going to fix a couple of issues in configure anyway (there seems to be a bit of a problem with lsb-release) so I can address this item as well.

**Comment by psubotic** [comment]
great! Thanks!

**Comment by b-scholz** [comment]
I would suggest that we have a special flag for solely building Souffle as a JNI library that omits some of the software dependencies pointed out by Paul.

I would suggest that per default everything should be built (as it is at the moment) and included.  Note sqlite3 is a default option for the stand-alone version of Souffle. It is used for debugging and cannot be omitted easily. Users can dump their data into a sqlite3 database and query their output data via sql queries.  Boost is required for wave/cpp and required for MAC OS X users. This cannot be switched off either.

The standalone version might be extended with an optional flag to switch off the JNI library and some software dependencies (e.g. libtool).  

I believe switching off software dependencies individually would not work so well in our current setup.

**Comment by b-scholz** [comment]
I believe over the summer-break we should put some effort into the build system. We have different scenarios:

- Build for a standard user (perhaps without JNI library)

- Continuous testing 

- Package build 

that might be adapted depending on the host system (MAC OS X / Linux).  In addition, we might want to consider a Windows 10 build. I recently read that they have a fully functional Linux-like subsystem.

**Comment by psubotic** [comment]
yes apparently Win 10 is very Linux friendly im told (last windows I used
was XP or something)

**Comment by psubotic** [comment]
ahh yes -- sorry -- this is the thread -- thanks @scyptnex . Jni is not so bad to have as default as it needs java and lets face it pretty much everyone has java. But the sqllite is non standard and 99% of people wont need a sql backend for souffle. Its really causing a pain on my mac and quite a few users use macs - so i suggest we take it out until we have the man power to make it an option.

**Comment by icesparrow** [comment]
Ok, I seem to have missed the most recent messages, I can put in a couple of --enable/--disable, say for JNI and SQL with a couple of autoconf macros to facilitate handlling such issues. I was also thinking of --enable-debug flag instead of debug features enabled via shell variables. That is so we can have a proper debug build build. Finally, there are some configuration errors related to the use of `lsb_release` which I want to get rid of for a while now.

JNI should be somewhat straightforward, although I have not looked into disabling SQLite yet, are there anything non-standard in there? Also, are there any other flags needed? We are finilising a submission now (deadline is the 15th of November) and I can get onto these issues after that.

**Comment by mmcgr** [comment]
#325 adds --disable-sqlite and --disable-libz flags to configure. (I see I missed the old SqliteRelationWriter so it's not quite done yet.)

**Comment by mmcgr** [comment]
#364 adds configure flags for jni
