### ISSUE TITLE
Explicit UB introduced by concurrent record table PR

### ISSUE THREAD

**Issue by OlivierHamel** [souffle-lang/souffle#2008]
```
class WriteCoutPrintSize : public WriteStream {
public:
    explicit WriteCoutPrintSize(const std::map<std::string, std::string>& rwOperation)
            : WriteStream(rwOperation, *static_cast<SymbolTable*>(0), *static_cast<RecordTable*>(0)), /// <<WTF?
              lease(souffle::getOutputLock().acquire()) {
        std::cout << rwOperation.at("name") << "\t";
    }
...
};
```

Clang 10 explicitly calls this out:
```
[build] /home/olivier/projects/souffle-neo/src/include/souffle/io/WriteStreamCSV.h:241:40: warning: binding dereferenced null pointer to reference has undefined behavior [-Wnull-dereference]
[build]             : WriteStream(rwOperation, *static_cast<SymbolTable*>(0), *static_cast<RecordTable*>(0)),
```

That this got through suggests that there's a serious hole in the review process.
Suggestion: Warning as errors required for all PRs.

There's some unsigned/signed comparison weirdness in `ConcurrentFlyweight` as well, but I haven't had the time to tell if it's just sloppy or if it's a mistake.

EDIT:
Bluntly that the same person both submitted a complex concurrent data structure *and* a blatant UB is alarming. Ought to either get the story of how/why this UB got introduced and review the DS with a fine comb.

**Comment by b-scholz** [comment]
It would be great if you can fix it.

**Comment by OlivierHamel** [comment]
I will. I've concerns past just that UB though, as noted in the edit.

**Comment by quentin** [comment]
Hi,
I remember this was a choice at some point during my dev:
- first, the class did not seem to be used. 
- second, if I remember correctly this class is not designed to access the record and symbol tables. 
- third the record table and symbol table here are never used. The code before my change was initializing the tables empty.

Sure, this should be sanitized by passing empty tables. I missed it before submitting, gcc was probably silent about it, I'll be vigilant.

**Comment by b-scholz** [comment]
This has been a design issue in the I/O interface. In general it is assumed that an I/O module requires a symbol table.
However, with one exception -  printing the sizes of a relation does not require symbol tables.
 
No harm is done (even it is UB), because the symbol table is never accessed in this I/O module. It is not a big issue but from an sw-engineering viewpoint it might not be ideal. 

We could fix this as follows:

1) We just pass on the real symbol table like in all the other modules (preferred)

2) We switch to a pointer semantics for symbol table and permit null pointers (might be ugly because of interface changes) 

3) We use C++17 optional<C> semantics (similarly ugly)

The solution 1) has the least impact to the interface.
