### ISSUE TITLE
Type system: Fails when Union type expands to different primitive types

### ISSUE THREAD

**Issue by limasierra** [souffle-lang/souffle#201]
Hi,

I ran into a problem with the type system. Consider this minimal example:

```
.number_type one
.number_type two

.type all = one | two

.decl A (i:one)
.decl B (i:two)

.decl F (i:all)
.decl E (i:all) output

A(1).
A(2).

B(2).
B(3).

F(X) :- A(X).
F(X) :- B(X).

E(X) :- F(X), !A(X), !B(X).
```

Expected output:

```
---------------
E
===============
===============
```

Actual output:

```
Error: Unable to deduce type for variable X in file minimal_3.dl at line 21
E(X) :- F(X), !A(X), !B(X).
--^-------------------------
Error: Unable to deduce type for variable X in file minimal_3.dl at line 21
E(X) :- F(X), !A(X), !B(X).
----------^-----------------
Error: Unable to deduce type for variable X in file minimal_3.dl at line 21
E(X) :- F(X), !A(X), !B(X).
-----------------^----------
Error: Unable to deduce type for variable X in file minimal_3.dl at line 21
E(X) :- F(X), !A(X), !B(X).
------------------------^---
```

As far as I understand, Soufflé has trouble to find the type when the union **all** would expand to **one** and to **two** in the same clause.

I checked with @HerbertJordan already. He is convinced this should be possible and considers it a bug in Soufflé.

Thanks, and
Kind regards,
Laurent

**Comment by b-scholz** [comment]
Yes - indeed that is a problem. The types in the head should may be super-types.

**Comment by HerbertJordan** [comment]
I think our current deduction is correct for the head and positive atoms in the body, but we have to exclude  negated atoms -- just as we exclude them for checking whether variables are bound.

We should extend the type check by (a) filtering out negative atoms for the initial check and (b) after we got a solution for the most general type T, check whether the negated atoms reference to sub-types of T. 

Should be a rather simple fix, not weakening any of our current checks. We just never stumbled across that case.

**Comment by scyptnex** [comment]
Discussed with bernhard,
potentially you cant ignore negated clauses:
```
.decl E(i:one)
E(X) :- F(X), !A(X).
```
This would work with the current type checker, but X should cause a conflict if you do not consider the `!A` clause.

The correct type semantics is that variables in a negated clause must be a _super-type_ of the declared column.
Then the constraints for the original example are:
```
subtype(X, all) && subtype(X, all) && supertype(X, one) && supertype(X, two) => X :: all
```

**Comment by HerbertJordan** [comment]
I tested your suspicion that ignoring the `!A` will cause a conflict, but it does not. Test for yourself:
```
.number_type one
.number_type two

.type all = one | two

.decl A(i:one)
A(1).

.decl F(i:all)
F(1).

.decl E(i:one) output
E(X) :- F(X).
```
Furthermore, I did not suggest to ignore negations, but to test them in an extra round. The proposed procedure will check exactly those constraints you have been enumerating.

To clarify, here an example based on the original code above:
```
.decl A (i:one)
.decl B (i:two)
.decl F (i:all)
.decl E (i:all)
E(X) :- F(X), !A(X), !B(X).
```
we currently try to compute the greatest common sub-type of all occurrences of X, thus of the types `[ all, all, one, two ]`, which does not exist due to our implicit assumption of disjunctive base types. Thus, the test fails.

My suggested fix:
- round one: only consider positive atoms: 
    - solve: subtype(X,all) && subtype(X,all) => X = greatest common sub-type of {all,all } = all
- round two: check for each negative atom whether the type X gets bount to is a sub-type of the computed type of X: 
    - check: subtype(one,X) && subtype(two,X) = subtype(one, all) && subtype(two,all) = OK

Note that composed, those are the same 4 constraints you asked for. Also note: in our implementation, the greatest common sub-type is not always a single type, it may be a set. So this example is a slight simplification of the actual use case.

**Comment by b-scholz** [comment]
Note that this is also related to aggregates as well. For aggregates we would need a similar technique. The type checker walks from the outer scopes to the inner scopes of a rule with aggregates. See issue #128.

**Comment by b-scholz** [comment]
Is this fixed?

**Comment by lyndonhenry** [comment]
Yes, I believe so; the test in tests/semantic/union_types/union_types.dl includes and extends slightly the original given program to produce behaviour as indicated below:

~~~
.number_type one
.number_type two
.symbol_type three

.type all = one | two

.decl A (i:one)
.decl B (i:two)
.decl C (i:three)
.decl D (i:three)

.decl G (i:one)
.decl F (i:all)
.decl E (i:all)

A(1).
A(2).

B(2).
B(3).

F(X) :- A(X). // no error
F(X) :- B(X). // no error
G(X) :- E(X). // no error

E(X) :- F(X), !A(X), !B(X). // no error
E(X) :- F(X), A(X), B(X). // error

C(X) :- D(X), !A(X). // error
~~~
