### ISSUE TITLE
Add support for real numbers

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#215]
Now that we have the sum aggregate - many people will want the average. Would be nice to have decimals in the result.

**Comment by b-scholz** [comment]
Few thoughts about different data-types: This might be a some work because some of our current data-structures rely on bit-encodes (e.g. brie).  For floating-point numbers, bit-encodings are less advantages. Hence, we need to rely on b-trees as an internal data-representation where the ordering criteria considers floating point numbers explicitly. Note this will only affect the performance for binary relations. In addition, the lexicographical order templates need to accommodate the new data-format. The last challenge will be if we have different sizes for an attribute of an relation. For example, if we have 4 bytes for integers, and 8 bytes for floating point numbers. Another issue is that convergence of the semi-naive evaluation. We need to use an epsilon to make the fixed-point loops converge.  To summarise, this is a software engineering challenge but I don't see any major issues on a conceptual level.

**Comment by HerbertJordan** [comment]
Implementation wise there would not be an issue if we would re-interpret floating point values as integers for the sake of storing it in relations and re-interpret it back whenever we read them.

However, bries may perform badly, since floating points values interpreted as integers are widely scattered throughout the domain space -- thus, they are not dense.

Another thing is: I'd propose to prohibit equality joins on float values right from the beginning through syntactic checks. People don't like to realize that summing up 10x the value of 0.1 is no 1. I would prohibit, or at least warn, whenever a rule defining an equality between two floating point values is formulated.

**Comment by b-scholz** [comment]
Fixed in issue #1256
