### ISSUE TITLE
Incorrect result with ADT?

### ISSUE THREAD

**Issue by bertram-gil** [souffle-lang/souffle#2161]
Hi guys, 

Consider the two programs in [this diff](https://www.diffchecker.com/zDTHgLey). 
I apologize for the complicated programs. However, the difference between them is quite small. 
Running these programs should produce the same results for rule O since O is not affected by the change. But running the left one returns an empty result, and running the right one returns
```
1	1	1	1
```

Please let me know if the program is too difficult to debug. I can try to find a simpler example. 
In the meanwhile, can you please confirm that this indeed is a bug?

I am not using any flags. Simply `./souffle prog.dl`

Souffle version I am using: 235a3bcd3811087208a7785b1583c01158541616
OS: Debian GNU/Linux 10 (buster) 5.4.134.1.amd64-smp

**Comment by b-scholz** [comment]
I suggest simplifying the example.I.e apply delta debugging and remove all rules - relations that are not necessary to reproduce your concern.

Do you have an idea which program is failing?

**Comment by bertram-gil** [comment]
Please checkout [this new diff](https://www.diffchecker.com/sO0kVy9V). I am afraid this is the most I could compress this example and the changes between them. If I make any more changes to the file then I am not able to reproduce this behaviour.
The example on the left produces an empty result for O. Whereas the example on the right produces
```
1	1	1	1
```
which I believe is the correct answer. 

My concern is that the change in rule `M` should have no affect on the result of rule `O`.

FYI: This example was produced by a new Datalog testing tool I've been working on :)

**Comment by b-scholz** [comment]
I would suggest that you trace the evaluation.

**Comment by b-scholz** [comment]
Print the inserted tuples in the interpreter and which rule is currently processed. There was a recent post about this.

**Comment by quentin** [comment]
Hi, 
One of the rule uses the `ord(symbol)` functor. The result of `ord` for a given value of the argument should not be considered deterministic in general. It only guarantees that during a run of the program `ord(x) = ord(y) <=> x = y`. **The documentation should probably be clearer on that point**.

In your examples, the simplest modification of the program can change the set or the order of produced symbols, thus each program may draw a different mapping from symbols to `ord` values. Note that the order in which symbols are produced may also vary with the thread scheduling, hence giving different `ord` mapping between two runs of the same program with the same inputs.

The rule `Y(ord(a)) :- X(a).` may produce different facts for each program. Since `Y` is indirectly used to compute `O`, it is possible, like in your example, that you won't have the same final result for `O`.

In your example, replace the rule for `Y` with `Y(1). Y(3). Y(5).` and you will observe the correct result.

**Comment by b-scholz** [comment]
Great catch!

**Comment by bertram-gil** [comment]
Ahh yes you are absolutely right @quentin. Thanks for clearing it up :)
