### ISSUE TITLE
Regression between 2.2 and 2.3

### ISSUE THREAD

**Issue by tchoutri** [souffle-lang/souffle#2278]
I have a datalog file (joined) that used to compile well, but now produces CPP code that makes g++ unhappy:

```
cbits/categorise.cpp:344:1: error:
     error: ‘SymbolTableImpl’ does not name a type; did you mean ‘SymbolTable’?
      344 | SymbolTableImpl symTable{
          | ^~~~~~~~~~~~~~~
          | SymbolTable
    |
344 | SymbolTableImpl symTable{
    | ^
[…]
```
[log.txt](https://github.com/souffle-lang/souffle/files/8792308/log.txt)

[categorise.dl](https://github.com/souffle-lang/souffle/files/8792306/categorise.dl.txt)

edit: @luc-tielen is investigating, since I'm using his Haskell bindings.

**Comment by luc-tielen** [comment]
Did some initial investigations. It's due to changing header files (which I have to manually update in souffle-haskell each time).

I tried upgrading everything to souffle 2.3, but now I'm getting a segfault in the C++ code. Idk yet if this is due to my small "C++ interop layer" or due to code in souffle.

I posted the gdb backtrace in the PR where I am doing the upgrade: https://github.com/luc-tielen/souffle-haskell/pull/65.


I did see that support for serializing ADTs etc was added, maybe that broke something? (Even though I don't use them?)

**Comment by b-scholz** [comment]
Could it be that you mix headers of different versions of souffle?

**Comment by luc-tielen** [comment]
@b-scholz Yes, but I did update them in my library after @tchoutri pointed it out to me.

Then I ran into the segfault I mentioned earlier, but that might actually have been due to my laptop not being correctly setup. 

I took another look at it today, and it seems like it is building fine on Ubuntu, but for OSX I still run into an issue building souffle itself. I made PR #2279 for this.

In the meantime I think this issue can be closed, and we can follow up the OSX issue in the other PR.
