### ISSUE TITLE
Fix warnings in compilation of Soufflé

### ISSUE THREAD

**Issue by pnappa** [souffle-lang/souffle#233]

**Comment by lyndonhenry** [comment]
The problem here is that many of the warnings are not the reponsibility of Souffle, but that of other libraries and programs. 

Warnings occur in three main places:

- wavelib (an external library from Boost, which we use as is and cannot maintain independently)
- scanner.cc (a file generated by Flex from scanner.ll, where the error is a result of what Flex does and not what we do)
 - RamStatement.h (one of our files, most definately our responsibility, so I've fixed it and done a pull request)

So unless new code causes new warnings to spring up, Souffle doesn't now generate any on its own.

**Comment by pnappa** [comment]
Reopening for two reasons: 

1) Clang still has additional warnings compared to gcc, entirely due to the `-Wpessmizing-move flag,` which warns on improper usage of `std::move` - simply removing all uses of `std::move` when mentioned allows elision to optimise properly. These occur in `AstParserUtils.cpp` and `parser.yy`.

2) My addition of mcpp means that a load more errors were introduced, the large majority of warnings are simply from a misconfiguration of configure.ac (the glaringly obvious one that I had found is `HOST_HAVE_STPCPY` is defined two times in several compilations of `mcpp-configed.H` (removing the first is sufficient to remove the warning, as a later case covers the ifndef scenario.

**Comment by pnappa** [comment]
Closing for now - the warnings for now have been fixed in #252 

This doesn't cover a lot of the warnings from mcpp, but fixing those require maintenance, and is outside our responsibility
