### ISSUE TITLE
Duplicated definitions on generated code

### ISSUE THREAD

**Issue by mingodad** [souffle-lang/souffle#2356]
When trying to build https://github.com/GaloisInc/cclyzerpp with the latest `souffle` I was getting several link time errors see here https://github.com/GaloisInc/cclyzerpp/issues/141 due to duplicated symbols at link time when trying to use more than one `souffle` generated sources in the same application/library.

But using the exact `souffle-2.3` builds without problems, probably a regression or unintended changes happened ?

**Comment by mingodad** [comment]
Hello @ruricolist can you make a pull request ?
Looking through your repository it seems that you have a fix for this.

**Comment by quentin** [comment]
As part of a larger set of changes, I added an option to specify a namespace for the generated code so that several programs may be instanciated: https://github.com/quentin/souffle/commit/2f86f7b770dfc1831e5375f7625fb72bcbf5a1ae

I might progressively contribute the branch in a near future.

**Comment by ruricolist** [comment]
In the meantime this patch can be used to allow Souffle to output files that can be compiled and linked: https://github.com/souffle-lang/souffle/compare/master...ruricolist:souffle:master

Note that either way, executables generated by linking multiple Souffle files will now be much larger (because the linker can no longer eliminate duplicate methods).
