### ISSUE TITLE
More Mathematical Functions

### ISSUE THREAD

**Issue by lyndonhenry** [souffle-lang/souffle#298]
Souffle currently only handles a basic set of mathematical functions (i.e. plus, minus, times, divide, modulo, exponent, etc). It might be good to extend this set to include some or all functions in math.h, making these native operations of the language. While as currently Souffle only supports integers, there would be limited use in something like a sin function at the moment, however if issue #215 is resolved, the applications are compelling.

**Comment by b-scholz** [comment]
For this we need to introduce a new data-type "float" (4 bytes). 
If the floating point number has the same length as RamDomain, it should be fine. 
Another problem is that for floating point numbers, we need to use BTrees only. 
Bries would not work because we won't have a dense number representation.
