### ISSUE TITLE
Logical Propositions

### ISSUE THREAD

**Issue by psubotic** [souffle-lang/souffle#30]
boolean expressions in single clauses to make more succinct code

**Comment by b-scholz** [comment]
Can you be more specific with examples?

**Comment by b-scholz** [comment]
I believe propositions (=tables with no attributes) have some relevance for optimizing rules. 
There are also other use cases. Please find below an example that might work:

```
.decl A(x:number, y:number) 
.decl B(x:number, y:number) 
.decl R(x:number, y:number)

// define a proposition (true or false value only) 
.decl my_check bool

// becomes true if there exists x and z for which the body holds; otherwise false. 
my_check :- A(x,10), B(10,z). 

// body can have a proposition instead of an atom like below
R(x,z) :- A(x,y), B(y,z), my_check.
```

**Comment by b-scholz** [comment]
This extension is necessary for optimising rules with multiple headers and rules that are expanded to DNF. There might be portions in the bodies that work as guards only and we would need to a rewrite mechanism that uses propositions as mentioned above. 

For example:

```
A(x1,x5), B(x1,x3) :- R1(x1,x2), R2(x2,x3), R3(x3,x4), , R4(x4,x5).
```
can be rewritten to 
```
A(x1,x5) :- R1(x1,x2), R2(x2,x3), R3(x3,x4), R4(x4,x5).
B(x1,x3) :- R1(x1,x2), R2(x2,x3), R3(x3,x4), R4(x4,x5).
``` 

Since the predicate `R3(x3,x4)` and the predicate `R4(x4,x5)` are not used for the actual computation of B, it is very tempting to remove `R3(x3,x4)` and `R4(x4,x5)` from the rule. However, this is semantically not correct, because if the query `R3(x3,x4), R4(x4,x5)` is empty, it has an impact on relation B.

With  propositions, the rule for B could be rewritten to
```
B(x1, x3) :-  R1(x1,x2), R2(x2,x3), I_R3_R4
I_R3_R4 :- R3(x3,x4), R4(x4,x5). 
```
Note that the proposition I_R3_R4 does not need to be re-evaluated as soon as it holds. It would result in an efficient implementation.

**Comment by psubotic** [comment]
yes this is required - changing the milestone

**Comment by psubotic** [comment]
I notice logicblox has nullary predicates - should we mimic this? also lets be sure we are in agreement over the semantics

**Comment by HerbertJordan** [comment]
Nullary relations should already be supported by the backend, i think it is only an issue in the grammar of the frontend that is preventing it (and then maybe some code implicitly assuming that there are always attributes).

To the semantic: a nullary relation P() is a set of tuples with no elements. There is only one such tuple, the empty tuple (). So P can either be the empty set {} or the set containing the empty tuple {()}. 

As a consequence, you can consider P() a boolean predicate in your datalog rules, where the {} state is the false state and the {()} is the true state.

In your code, if you have
```
.decl R()
.decl P()
P() :- !R().
```
the stratification due to the negation will process a stable state for the relation R first. Since we always look for a minimal fixpoint, it will be the empty set {}.

The evaluation of `P() :- !R()` will then check whether R is empty -- which it is is -- and add the tuple () to relation P, updating P's state to {()}. Thus, P could be considered true.

The important thing is that those relations, although they might be considered just boolean predicates, are as well subject of the stratification of negations. As a result, we do not have to solve arbitrary SAT problems.

One more remark: the fact file of a boolean relaiton would be either an empty file for {} or a file with a single `\n` for {()}.

**Comment by psubotic** [comment]
thanks for that explanation Herbert. Makes sense. Ill take care of it. I think we will go with the nullary pred syntax and not the Bool syntax for now.

**Comment by b-scholz** [comment]
I wrote a small little test-case for nullary relations. Please could you add this to the tests/semantic directory. The input/output qualifier for nullary relations does not work yet.

[nullary.zip](https://github.com/souffle-lang/souffle/files/327726/nullary.zip)

**Comment by b-scholz** [comment]
There is another observation. If we use a nullary relation in the body of a rule, I wonder whether the C++ compiler is smart enough to hoist the conditional check outside of the loop. If not, we would need to improve the code generation.
