### ISSUE TITLE
Three features to speed up development and make it more fun

### ISSUE THREAD

**Issue by HerbertJordan** [souffle-lang/souffle#36]
The following features would ease the development process
- [x] support for **out-of-source builts** so that release, debug and gcc/clang versions can co-exist without the need of constant re-configuration and re-building
- [x] a **faster way to run individual integration tests** selectively to investigate bugs; running all of them and waiting for 20 minutes until your failing test is processed the first time so that you get the test runner you can then run manually is not much fun
- [x] **run tests in parallel** so that developers have not to wait for lots of tests to be processed while (n-1) of their n cores are idle

**Comment by b-scholz** [comment]
1) Pre-defined out-of-source builds would be wonderful. In principle, out-of-source builds already work without problems. For example you can type

```
sh boostrap
mkdir build
cd build
../configure
```
and `make distcheck` which uses out-of-source builds works as well. 

I believe what you are after are a set of hard-coded out-of-source builds such as debug and release, i.e., 
```
sh boostrap
mkdir debug
cd debug
export CXXFLAGS="-g -O0" 
../configure
make 
```
and
```
sh boostrap
mkdir release
cd release
export CXXFLAGS="" 
../configure
make 
```
Is this correct?

2) I don't believe in fast integration tests in general for the integrity of the project. However, for local testing you have a point. It would be great to have an environment variable that controls the configuration sets so that not all compile/interpretation configurations are enumerated.  The behaviour of the configuration is controlled by the following macro in tests/testsuite.at.
```
m4_define([CONFS], [[], dnl interpreter
 [-c],                  dnl compilation 
 [-j8],                 dnl interpreter / parallel execution
 [-c -j8],              dnl compilation & parallel execution 
 [--auto-schedule -o testprog],  dnl auto-scheduling & compilation
 [-p profile.log],      dnl interpreter & profiling
 [-c -p profile.log]    dnl compiler & profiling
])
```
By being able to overwrite the defined list by an environment variable would be great. Kostyantyn is an expert on this. Perhaps he can help.

3) You can already run the tests in parallel using an environment variable. Type 
```
export TESTSUITEFLAGS=-j3
make check
```
for example. Don't forget the number of processes; otherwise for each test a new process is spawned and it will bring down your computer, i.e., we have more than 1000 test cases.

**Comment by b-scholz** [comment]
I believe all issues are implemented/answered. Is this correct?

**Comment by HerbertJordan** [comment]
It seems like issues 1 and 3 have been resolved. We should document such kind of features. For instance, the parallel execution of the checks, the out of source build, and the way to create a debug build should be covered on the README page.

For issue 2: in your reply to provided a way to reduce the overall set of integration tests to be run. While also nice, what I was actually asking for is a possibility to run an individual test selectively.

For instance: When I am adding a new feature, I create an integration test `fancy_feature_test_17`. You run the test suite, and I have to wait probably 20 minutes until my new test is processed, before I noticed that I had e.g. an extra new-line at the end of some of the result sets. Which can be quickly fixed, and i can re-run the test with the runner somewhere in the testsuite subdirectory. To see whether everything works -- before I have to wait another 20 minutes to see whether now all tests pass.

Is there a way so that I can -- right at the start -- just run my `fancy_feature_test_17` directly, get it working and then run the full testsuite once?

**Comment by b-scholz** [comment]
Yes you can. Go to the tests directory. Autotest will generate a script called ./testsuite. 
You can run an individual test with 
```
./testsuite 17
```

Also you can go straight into the tests/testsuite.dir directory and go the failing tests. There you will find a run script which you can invoke to rerun a test.

**Comment by HerbertJordan** [comment]
OK, i wasn't aware of this feature.

How do I know the number of a newly created test case?

**Comment by b-scholz** [comment]
Have a look at the options of the ./testsuite program with `--help`. It has the option `-l` that gives you all the test cases and their numbers. 

Indeed - we need to document all this on the wiki page.

**Comment by HerbertJordan** [comment]
Documented by  1ccd10ca08cfe .
