### ISSUE TITLE
Counter functor

### ISSUE THREAD

**Issue by Kostast23** [souffle-lang/souffle#362]
While experimenting with the counter functor, I wrote the following trivial program
```
.decl A(a:number)
.output A

A(1).

A($) :- A(1).
A($) :- A(1).
A($) :- A(1).
```
which to my surprise outputs
```
1
3
5
7
9
11
```

In contrast this program
```
.decl A(a:number)
.output A

A(-1).

A($) :- A(-1).
A($) :- A(-1).
A($) :- A(-1).
```
outputs
```
1
3
5
-1
```

**Comment by b-scholz** [comment]
That is a good one! I like it. 

There is an underlying problem that relation A is recursively defined. Basically, to compute ```A``` a standard worklist/fix-point algorithm is generated. Your rules may be evaluated several times until a fix-point is reached. The problem is some intricate detail that A($) produces one which becomes an element of the delta relation of the second iteration. Hence, the worklist algorithm is forced to evaluate again. In the second version the counter state does not produce 1 to validate A(1) and hence it does not come to a second iteration. Anyway, the problem is the recursion. By rewriting the example slightly you would get the expected result. 

```
.decl A(a:number)
.decl B(a:number)
.output A

B(1).

A($) :- B(1).
A($) :- B(1).
A($) :- B(1).
```

There is no recursion and  for such a scenario, you can assume that each rule is executed only once.
In the recursive case, this cannot be assumed and causes some interesting behaviour.

**Comment by Kostast23** [comment]
That's what I thought is happening. However, why is 1 part of the delta relation of the second iteration if it is already a fact? Is $ responsible for this behaviour?

Also, this program
```
.decl A(a:number)
.output A

A(0).

A($) :- A(0).
A($) :- A(0).
A($) :- A(0).
```
outputs
```
0
2
4
```
I suppose that A($) produces 0 but it is not added to the delta?

**Comment by b-scholz** [comment]
The RAM code explains this behaviour. You can see the RAM Code by adding the flag ```--debug-report=<file>.htm```. The RAM code is the relational algebra machine that executes the Soufflé program in a relational/imperative fashion. The problem is that the counter is fetched twice for each rule. Once to check whether the value is in A and then when the projection occurs. This RAM code snippet is the culprit for the behaviour:

```
INSERT 
			IF ∃ t0 ∈ _temp1_A WITH t0.c0=number(0) WHERE (autoinc()) ∉ A
				PROJECT (autoinc()) INTO _temp2_A;
```

For the first rule, the condition fails because autoinc() produces zero. For the second two rules it will work. 

I am very much tempted to remove the auto-increment functor from Soufflé due to it its unpredictable behaviour. Alternatively, we could find a better semantics (one auto-increment invocation per rule only / no recursion / etc).

**Comment by b-scholz** [comment]
Note that we make the assumption in the translation that the evaluation of the same expression (on the same data) yields the same value. This is not the case for autoinc().
