### ISSUE TITLE
Subtyping of records

### ISSUE THREAD

**Issue by gkastrinis** [souffle-lang/souffle#380]
I have the following issue and I would like to know whether I am doing something wrong or if it is a design choice from your part. If it is the latter, I would also like to know how possible it would be to change.

When I have a union of two "simple" types, it works fine. E.g. `a.dl`
When I try to do the same with record types I have issues. E.g. `b.dl` (same records), `c.dl` (same arity, different types), `d.dl` (different records entirely).

The behavior I see (it's not even an error) is the following

```
souffle: TypeSystem.cpp:301: virtual std::__cxx11::string souffle::getTypeQualifier(const souffle::Type&)::visitor::visitType(const souffle::Type&) const: Assertion `false && "unknown type class"' failed.
[1]    27616 abort (core dumped)  /opt/souffle/src/souffle d.dl
```

When I try to do the union in-place (`e.dl`) I get a syntax error

```
Error: syntax error, unexpected |, expecting end of file in file e.dl at line 3
.type Cy = [x:symbol, y:number] | [x:symbol, y:symbol, z:number]
--------------------------------^--------------------------------
1 errors generated, evaluation aborted

```

Is there some way to make this work?

[a.dl.txt](https://github.com/souffle-lang/souffle/files/995661/a.dl.txt)
[b.dl.txt](https://github.com/souffle-lang/souffle/files/995659/b.dl.txt)
[c.dl.txt](https://github.com/souffle-lang/souffle/files/995660/c.dl.txt)
[d.dl.txt](https://github.com/souffle-lang/souffle/files/995657/d.dl.txt)
[e.dl.txt](https://github.com/souffle-lang/souffle/files/995687/e.dl.txt)

**Comment by b-scholz** [comment]
Hi George,

No - unfortunately we don't have polymorphic records. That would be a great feature but we haven't got it implemented. 

Currently, union types are available for primitive types only, and they do not need a specific implementation (it is always a machine word). However, for record types this is a different story because the numbering of records is not unique. There could exist the same record number for two different record types. 

An implementation technique for unified record types could be a unique numbering for records that are unified in another type declaration (i.e. for unified record types there exists one shared counter only). This implementation requires probing the existence of records in different type tables. Alternatively, we can have an additional type field for each tuple. This is a classical runtime/memory trade-off.   

Overall, the implementation would require some effort. I can put it down as a student project for next semester (i.e. adding OO to logic) but it won't happen tomorrow. Would you be interested helping in the implementation - if so; let me know.

**Comment by b-scholz** [comment]
We have a student working on this issue over the summer break. 

Do you have any specific wishes on how it will be implemented?

Also as soon as it is implemented I would like to retire the counter. Is this ok?

**Comment by yanniss** [comment]
Would there be a performance penalty if all types are tagged? I expect so. The issue is not just distinguishing record types in a union, but also distinguishing a record and a non-record, e.g.,

.type BinaryExpr = [ op: symbol, opnd1: Expr, opnd2: Expr ]
.type Expr = BinaryExpr | symbol

Generally, I'm not sure what to describe as the highest priority w.r.t. this feature. The limitations are unnatural sometimes, but we've learned to live with them.

**Comment by b-scholz** [comment]
Tagging all values with type information may not be a good idea (we may slow down quite a bit).

I would suggest that we tag record values only. However, you can box primitive types (like in Java).

```
.type SymbolType = [s:symbol]
.type BinaryExpr = [ op: symbol, opnd1: Expr, opnd2: Expr ]
.type Expr = BinaryExpr | SymbolType
```
Would that be ok?

**Comment by olligobber** [comment]
Even with the suggestion above of
```
.type SymbolType = [s:symbol]
.type BinaryExpr = [ op: symbol, opnd1: Expr, opnd2: Expr ]
.type Expr = BinaryExpr | SymbolType
```
the type information would have to be carried with the values, so that a relation like
```
.decl T(e : Expr)
T(["=", a, b]) :- E(["=", a, b]), a = b.
```
could be evaluated correctly, as without type information it is impossible to tell if `a` and `b` are both `SymbolType`, both `BinaryExpr`, or distinct types.
