### ISSUE TITLE
Request: Static linking

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#414]
We're building for a couple architectures, and we'd like to be able to build the binaries once and move them around.  Currently when we try this we get the following error:

```
$ ~/tmp/sean-souffle/souffle -c db.dl
Error: failed to locate souffle preprocessor
```

**Comment by scyptnex** [comment]
Some notes should we get around to this:

1)  souffle builds a few auxilary things (like the preprocessor executable, the "makefile" souffle-compile.sh) which are currently external to the acutal souffle binary
2)  souffle assumes that it should configure and execute datalog binaries *with the same configuration* that was used to compile souffle. i.e. you cant assume that we can compile generated code on a different machine even if the souffle binary runs on them, only if the souffle binary was compiled on them

As a stopgap you can make an executable 'blob' by
* perform an external build (mkdir build; cd build; ../configure)
* remove the build files (.o files etc)
* zip it up and copy that around

Though doing so might lead to errors because of (2)

For Souffle to run as a standalone executable we'd have to rethink the architecture a bit
Improving the Souffle infrastructure is related to #150

**Comment by seanmcl** [comment]
@scyptnex could you please elaborate on 2.  Is this because the binaries are not statically linked and there may be missing library dependencies?

**Comment by psubotic** [comment]
I think what Nic is saying that the configure script makes some assumptions
about the target system and uses that to generate scripts like
souffle-compile (that invokes a C++ compiler) to create a binary.

But if you know already the set up in your target machines i.e., have g++
version XX etc. you can compile for several architectures and have fixed
souffle-compile scripts.

**Comment by psubotic** [comment]
handling this offline so I'm closing this for now.
