### ISSUE TITLE
Index out of bounds in aggregation

### ISSUE THREAD

**Issue by gkastrinis** [souffle-lang/souffle#421]
The following code reports and index out of bounds error

```
P("hello",1).
P("hello",2).
P("hello", 3).
P("22hello", 3).
.decl P(x:symbol, y:number)
.decl t(x:symbol, y:number)
.output t

t(x, n) :- n = count : P(x, _).
```

```
Error index out of bounds in call to SymbolTable::resolve.
```

If I change the aggregation to the following, it works

```
t(x, n) :- P(x, _), n = count : P(x, _).
```

**Comment by b-scholz** [comment]
This is related to the witness problem. The first version of the program should report a semantic issue because the variable x is used outside the scope of the aggregate. This is also reported in issue #128.
We have also one lecture slide about this issue in our tutorial.

**Comment by gkastrinis** [comment]
The following example (that is similar to the first one) is actually working with results!

```
foo(1, 2).
.decl foo(x0:number, x1:number)
.decl t(x0:number, x1:number)
.output t
t(x, c) :- c = count : foo(x, _).
```

```
cat t.csv
1       1
```

**Comment by souffle-lang** [comment]
This is just by chance. If you analyse the generated code, you will see that the generated code is faulty. The current semantic model does not permit to export values of x to the outer scope. Since all witnesses may need to be enumerated for a single value of c. To obtain a semantically correct program, that you rewrite the rule as follows: 
```
foo(1, 2).
.decl foo(x0:number, x1:number)
.decl t(x0:number, x1:number)
.output t
t(x, c) :- foo(x,_), c = count : foo(x, _).
```
