### ISSUE TITLE
Feature: exists solution

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#452]
Sometimes we only care if a solution exists.  There may be 10^10 of them, but we just want one example.  It would be great if souffle could support this use case without timing out generating all solutions.

**Comment by b-scholz** [comment]
Can you give us an example?

**Comment by psubotic** [comment]
I think what Sean means is this (correct me if i'm wrong Sean):

P(x, y) :- .....complex body

What often happens if we want to know existence is we use nullary
relations. We encode this will nullaries now: e.g.,

Q() :- P(x, y). Now P might be very very large but this information is not
needed we only need to be in the domain of top/bot (side note for Bernhard:
the stuff we discussed abstract bottom up may help here?)

I think I discussed this with you a while back

**Comment by seanmcl** [comment]
Yes, Paul's example is correct.  A concrete example is 

```
.decl reachable(ip1: int32, ip2: int32, port1: int16, port2: int16)
.decl safe(instance: Instance)
safe(I) <-
   instance-has-ip(I, Ip), 
   !reachable(Ip, _, _, _).
```

**Comment by mmcgr** [comment]
This seems like a more complicated version of #48 .

**Comment by b-scholz** [comment]
We have an initial version for optimising existentials. Can you give it a try?

**Comment by b-scholz** [comment]
This was the pull-request #563.
