### ISSUE TITLE
Build system should stop on errors

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#504]
I was just building Souffle in Docker and ran into this:

```
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT mcpp-main.o -MD -MP -MF $depbase.Tpo -c -o mcpp-main.o mcpp-main.c &&\
mv -f $depbase.Tpo $depbase.Po
depbase=`echo mcpp-directive.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -MT mcpp-directive.o -MD -MP -MF $depbase.Tpo -c -o mcpp-directive.o mcpp-directive.c &&\
mv -f $depbase.Tpo $depbase.Po
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [libsouffle_la-MagicSet.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [libsouffle_la-TypeSystem.lo] Error 1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make[2]: *** [libsouffle_la-DebugReport.lo] Error 1
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_VERSION=\"1.1.0\" -Wall -std=c++11 -O3 -DUSE_LIBZ -fopenmp -MT libsouffle_la-AstSrcLocation.lo -MD -MP -MF .deps/libsouffle_la-AstSrcLocation.Tpo -c AstSrcLocation.cpp -o libsouffle_la-AstSrcLocation.o >/dev/null 2>&1
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -DPACKAGE_VERSION=\"1.1.0\" -Wall -std=c++11 -O3 -DUSE_LIBZ -fopenmp -MT libsouffle_la-RamRecords.lo -MD -MP -MF .deps/libsouffle_la-RamRecords.Tpo -c RamRecords.cpp -o libsouffle_la-RamRecords.o >/dev/null 2>&1
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
...
```
It would be nicer if Souffle stopped at the first error and did not continue.  I didn't notice this for a long time because I thought the build was working.

**Comment by mmcgr** [comment]
Make will not start new jobs after an error is encountered, but will finish currently running jobs. That's what's happening at this point
```
make[2]: *** [libsouffle_la-MagicSet.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```
This does make errors hard to immediately notice, especially when the jobs still running produce a lot of text. It's not practical to kill the running jobs, though, since that can cause more problems. Dividing jobs up into smaller components can reduce the output produced after an error occurs, but I think most jobs are already as fine grained as they can be, so there's not much scope for that.

If you re-run Make, then already completed jobs aren't run again so you can see the error sooner - and running single threaded after an error occurs also helps. You can also try running with stdout piped to file so you can see error messages more easily - but which messages go to stdout and which stderr is a little inconsistent between tools and environments so this is not reliable.

**Comment by mmcgr** [comment]
Closing this, but feel free to reopen if you have more to add.
