### ISSUE TITLE
Question about magic set transform

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#539]
Here's an example transformed predicate from the debug report:

```
?24?tqlquery__and?24?2(PublicIp,EphemeralPort,Eni,Cidr,Instance) :- 
   ?24?tqlquery__or?24?1(Cidr),
   cidr_matches_public_ip(Cidr,PublicIp),
   ?24?tqlquery__or?24?0(EphemeralPort),
   instance_has_eni(Instance,Eni),
   reachable_public_tcp_udp(+abdul0_dir/ingress_s,+abdul1_proto/6_s,Eni,+abdul2_port/80_s,PublicIp,EphemeralPort),
   +abdul0_dir/ingress_s = "dir/ingress",
   +abdul1_proto/6_s = "proto/6",
   +abdul2_port/80_s = "port/80".
```

Why do the variable constraints come after the clause using them?  I thought that Souffle used the clause order from first to last to constrain variables.

Thanks.

**Comment by azreika** [comment]
Since the added constraints are all equality constraints binding variables to constants, the `ResolveAliasesTransformer` transformation (which is run immediately after magic set) should replace all occurrences of "+abdulX_*_s" with constants anyway, so this shouldn't affect anything as far as I know.

**Comment by seanmcl** [comment]
Thanks.
