### ISSUE TITLE
RPM for Oracle Linux

### ISSUE THREAD

**Issue by jgsuess** [souffle-lang/souffle#547]
Thanks to recent updates we are now able to use the deb package and ppa that is on offer for internal work, and it has made a substantial difference in work.
I am not an expert in RH land, but would love to have an RPM, as we have to ship in Oracle Linux. I know that one of the major drawbacks is the lack of gcc5.
I would invite comment on this ticket re: effort and steps required, as I know use of Oracle Linux might be marginal in the target user community.

**Comment by mmcgr** [comment]
The gcc available in the standard repos is 4.8.5. Even though it doesn't fully support c++11 that's enough to build souffle, although provenance will not work. There may also be random future breakages since it's not supported, but it's unlikely.

Your other problem will be mcpp. That's not in the standard oracle linux repositories so you will need to install it separately.

I tested with a docker container for Oracle Linux Server release 7.4. This was enough to build souffle
```
yum install -y autoconf automake bison clang doxygen flex gcc-c++ git kernel-devel ncurses-devel sqlite-devel libtool make mcpp pkg-config python sqlite sudo zlib-devel

yum install http://dl.fedoraproject.org/pub/fedora/linux/releases/27/Everything/x86_64/os/Packages/l/libmcpp-2.7.2-19.fc27.x86_64.rpm
yum install http://dl.fedoraproject.org/pub/fedora/linux/releases/27/Everything/x86_64/os/Packages/m/mcpp-2.7.2-19.fc27.x86_64.rpm

git clone https://github.com/souffle-lang/souffle.git
cd souffle
./bootstrap && ./configure && make
```

It looks like mcpp is the main challenge, although a slightly more recent g++ would also be great to have.

**Comment by mmcgr** [comment]
Note that mcpp was built into souffle in the 1.2.0 release. If you don't need any of the bugfixes and enhancements since then, the 1.2.0 deb may be an easier starting point for an rpm

**Comment by b-scholz** [comment]
For generating the package, we would need to have:

- a RH/CENTOS/Oracle build environment in travis-ci 

- a package building script for RH/CENTOS/Oracle packages  (NB: at the moment we have only package building scripts for Debian, Mac OS X, and brew).

**Comment by jgsuess** [comment]
Thanks, that is a fair bit shorter than what we have already. I will try and see if that also works on OL6. If not, I will see if I can push for 7. We have an engineering day here, where we are allowed to look left and right, so I might check what it takes to write the spec-file for RPM.

**Comment by b-scholz** [comment]
This is also related to issue #537.

**Comment by b-scholz** [comment]
This is also related to issue #125.

**Comment by mmcgr** [comment]
As of #674 we're testing an rpm repository: https://bintray.com/souffle-lang/rpm-unstable
You can install the repo for CentOS7 with https://dl.bintray.com/souffle-lang/rpm-unstable/centos/7/x86_64/souffle-repo-centos-1.0-1.x86_64.rpm

The repo contains an rpm of mcpp (the same version as is in the fedora repo) and the latest build of souffle from souffle-lang master.

If that doesn't work with OL7 then the steps to build one would be similar to what's in #674 (which is a little hacky and hard-coded, but functional). OL6 would have compiler issues since that only goes up to gcc 4.4.7.
