### ISSUE TITLE
Using souffle with 64 bits numbers

### ISSUE THREAD

**Issue by aeflores** [souffle-lang/souffle#559]
I have been trying to use souffle with 64 bits numbers. In principle, it should work by defining RAM_DOMAIN_TYPE to be int64_t  (according to src/RamTypes.h). However, this is not enough. 
There are at least a couple of places where the implementation is hard coded for 32 bits.

The ones that I found so far are:
1. in src/AstSemanticChecker.cpp, line 118, the range of the constants is checked according to the 32 bits range.
`if (idx > 2147483647 || idx < -2147483648) {`
`           report.addError("Number constant not in range [-2^31, 2^31-1]", cnst.getSrcLoc());`
`  }`

2. in /src/CompiledRamRecord.h, line 80
`static const std::size_t NUM_BLOCKS = 1 << (sizeof(RamDomain) * 8 - 20);`
The compilation gives me the following error when RamDomain is 64 bits:
`error: right operand of shift expression ‘(1 << 44ul)’ is >= than the precision of the left operand`
I am not sure what is the right fix for this one.

Once I changed these two points, I am able to compile souffle programs that manipulate 64 bits numbers but the results are truncated at some point upon printing (E.g. the number 0x100000001 is printed as 1). I know this is the case because if I use the C++ API, I get the correct results.
Could someone point out where in the code this might be happening?

Is there any other point where I should be careful? 
If we address these points, we could make souffle truly generic with respect to the type of numbers it supports.

**Comment by cfallin** [comment]
I dealt with this just a few weeks ago in the branch that @pratikfegade and I are using. These were the changes I made:

1. Switch the type in `RamTypes.h`: [commit](https://github.com/cfallin/souffle/commit/3e5a8f38c372e84ad5a029f0a8448b80b816075b)
2. Update range checks in the AST validator (your item 1), allowing 64-bit literals: [commit](https://github.com/cfallin/souffle/commit/5439122d3ef88ee29a968bcbdcabdefaa2cfb2d1)
3. Fix string/integer conversion for CSV and SQLite inputs and outputs: [commit](https://github.com/cfallin/souffle/commit/67b28c86d64357f43054bd99c74e8a7002c766c7)
4. Change `RecordMap`. The two-level structure needs to be extended somehow in order to not have an impossibly large array of block pointers (the 2^44 you see in the error). At first I chose to simply make the top level a hash table (commit)[https://github.com/cfallin/souffle/commit/31f4f4a9c2922ff278ea856879e06d025f39d542], but then for better performance, created a hybrid data structure with the original array of block pointers for < 2**32 and a hash table for "high blocks": [commit](https://github.com/cfallin/souffle/commit/555f921f62f4153c7e60ed5ef719056b9ac073ea)
5. Add `ul` suffix to integer literals emitted in C++ code so that values are not silently truncated by 32-bit math: [commit](https://github.com/cfallin/souffle/commit/cce7f7469bc407c002a3428efb98d9950a19cf28)

I'm happy to contribute this back as a PR, perhaps with `#ifdef`s, if folks think it would be useful...

**Comment by aeflores** [comment]
Great! I am glad you took care of this!

**Comment by mmcgr** [comment]
We've talked about 64 bit in the past, but decided to stay with 32 bit for the lower memory use. Even so, the ability to use 64 bit should be more functional. As you found, 32 bit is assumed far more often than it needs to be.

I would like to refactor to use RamDomain/AstDomain exclusively, but there are some design decisions involved in there (and the SQLite code gets uglier) that are still being considered.

**Comment by mmcgr** [comment]
In #569 I made similar changes to cfallin, but kept the existing defaults. Souffle builds, and works, with 64 bit RamDomains.

I kept RecordMap as an array of pointers to blocks, using vector for a resizable array. At this point it's pretty close to a custom implementation of std::deque with larger blocks. If records are heavily used then some benchmarking of alternatives is needed.
