### ISSUE TITLE
Existential optimization var names

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#636]
https://github.com/souffle-lang/souffle/pull/563/files is awesome.  It would be a little nicer if the existential variables didn't need to be called `_`.  For example, it would be great if the following programs were equivalent, termination wise

```
.decl p(x: number) output
.decl q(x: number)

 p(0) :- q(X).  // or _X or any other legal variable name 
q(0).
q(N+1) :- q(N).
```

and 

```
.decl p(x: number) output
.decl q(x: number)

 p(0) :- q(_).
q(0).
q(N+1) :- q(N).
```

**Comment by seanmcl** [comment]
This is not just a syntactic nicety.  For example:

```
.decl p() output
.decl q(x: number)
.decl r(x: number)

p() :- r(_), q(_).
q(0).
r(0).
q(N+1) :- q(N).
```

works but 

```
.decl p() output
.decl q(x: number)
.decl r(x: number)

p() :- r(X), q(X).
q(0).
r(0).
q(N+1) :- q(N).
```

should also work, and requires a non `_` name.

**Comment by b-scholz** [comment]
We will look into this optimisation. I will discuss with Abdul.

**Comment by azreika** [comment]
For your first point: currently, when singleton variables are used, a warning is issued but the variable isn't changed to an unnamed variable internally. I'll pull up a change for that soon! This should make the first two programs you gave semantically equivalent (and terminate with the existential transformer).

**Comment by azreika** [comment]
For your second point - with regards to the following program:
```
.decl p() output
.decl q(x: number)
.decl r(x: number)

p() :- r(X), q(X).
q(0).
r(0).
q(N+1) :- q(N).
```
If a relation is only used existentially (i.e. we only need to check if it contains any tuples/values at all), then we can remove all its recursive rules. This is because a recursive rule for a relation `R` can only be true if there already exists some value in `R`, and so checking if the base cases ever hold suffices for an existential check. This is the basis of the optimising transformer for existential relations.

Once you have a rule like `p() :- r(X), q(X).`, the value that we want from the relation `q` now has to be a particular one; in this case, the value `X` has to also be in the relation `r`. This means we can't just rely on the base cases of `q` anymore, as an appropriate value `X` might be found using a recursive rule.

For example, if we modified the program to:
```
.decl p() output
.decl q(x: number)
.decl r(x: number)

p() :- r(X), q(X).
q(0).
r(1).
q(N+1) :- q(N).
```
Then we would need to use the recursive rule once to generate the appropriate `X` value (1, in this case).

The theory behind the current transformer therefore doesn't cover this case, and should only be used for relations that are queried in a purely existential manner. For your given case, I believe it is natural to not expect termination, as we can only know at run-time whether `r` and `q` will ever have coinciding values, and once we begin to look at `q` we try to fully compute it.
