### ISSUE TITLE
Souffle C++ files too large

### ISSUE THREAD

**Issue by pratikfegade** [souffle-lang/souffle#638]
Hi

Would it be possible for Souffle to generate multiple C++ files instead of one? We use Doop, the Java pointsto analysis written in Souffle, and Souffle generates a 50K like C++ file which takes 10-12 minutes to compile, thus slowing down the development cycle. Multiple files could exploit incremental compilation thus speeding up the debugging cycle.

Pratik Fegade

**Comment by b-scholz** [comment]
I measured the compilation performance. In theory, we could split the code generation of the fix-point calculation into different files. An indication whether it works is given below:

real	1m26.213s for the whole C++ program (for context-insensitive)

real	0m16.171s for the C++ program with an empty runFunction<>. 

This gives me hope to separate the strongly connected components of the dependency graph in various cpp-files as separate functions. That may speed up the compilation. 

By the way - which computer are using - a small laptop?

**Comment by pratikfegade** [comment]
I am not sure why the file takes so long to compile on my workstation. I am using a context sensitive analysis with a lot of relations being dumped (and hence the file would contain code to dump them to files), but I am not sure why such a big discrepancy.

**Comment by mmcgr** [comment]
This seems to be the same issue as #740, even though profiling was not involved. I expect #741, now in master, will have improved this issue as well as that.

There have been substantial changes to the code generation since this issue was opened so I'm closing it, but I am also working on other ways to improve compilation performance so if you continue to have problems with compilation, do report them.
