### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by icesparrow** [souffle-lang/souffle#67]
I think now is the time to think about an actual release of Soufflé. Without a stable release it would be difficult to get into various repositories we have talked about. I suggest that we create a protected branch for the first release and start working on making it bullet-proof: no new functionality or features, just bugfixes and/or maybe some additional tests. If some new functionality comes in, then it can go to the master branch. Of course we need to discuss which features should actually go into the release. Any suggestions?

**Comment by b-scholz** [comment]
Good point!

Ideally, the release is done fully automatic. I feel we need to automate this process. For this process we need to do the following:
- extend the souffle-compile.in script so that if no OpenMP is installed, we don't bomb out running our test cases (important for MAC OS X build because openmp is not part of xcode)
- resolve the pre-processor issue on MAC OS X (currently the test suite would fail on some/all installations using the standard pre-processor clang/cpp )  
- extend the travis-ci script so that the deployment is done automatically 
https://docs.travis-ci.com/user/deployment/releases

Regarding the actual features; I would suggest that a release is just a snapshot of the project at a given point in time. We should not incorporate features into the master, if they are not stable and irrelevant for the project.

**Comment by scyptnex** [comment]
On part 3 now (at least as a prototype for debian packages).

Expect version 0.0.1 pretty soon

**Comment by b-scholz** [comment]
All aforementioned points have been completed. Unfortunately, we have still few things to do getting the release to work. Kostyantyn and I raise the following issues:

 * OpenMP is still an open issue for MAC OS X: we would need to build / create the OpenMP library on the fly.
 * Renaming `wave` to `souffle-wave` to avoid name clashes (there might be other tools around named wave)
 * Autotest has an old oracle group email that is unreachable from outside the Oracle network. I would suggest to replace it by a google mailing list email address
 * The souffle-compile.in script has few issues. It might be better to not assume that bash is installed; perhaps we use a standard shell "sh" instead
 * Provide options to disable souffle-wave if boost is not installed and use the standard cpp or SOUFFLECPP instead. 
 * The semantic versioning of the packages are hard-coded. We would like that they semantic versioning is picked up automatically.
 * Nic's raised issue about the Debian process hasn't been addressed yet.

**Comment by b-scholz** [comment]
I believe all points - except two  - we have completed or they are close to completion. It seems that we cannot get OpenMP to run on MAC OS X since Apple's clang++ was not compiled with OpenMP. I suggest that we might want to use grand central dispatch (GCD) or any other standard thread pooling library. The other issue is wave-cpp. I would dispute now that it would be good to have a fallback to the standard cpp on the system. It seems that pre-processors are heavily dependent on the C compiler, e.g., clang's and gcc's cpp have different behaviours. Hence, I suggest to have "wave" as a standard cpp. 

Perhaps down the line we could rewrite wave in such a way so that it becomes independent of boost - at the moment I am not fussed about the boost dependency for the preprocessor only.
