### ISSUE TITLE
Magic-sets for negation

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#716]
Is implementing magic-sets for programs with negation in the roadmap?

Thanks.

**Comment by azreika** [comment]
Extending magic-set to handle negated body literals is a fair bit more complex, because it messes with program stratification. There is a way to handle it, but it involves changes to the actual backend evaluation procedure (instead of just being a program-rewriting transformation).

We're not in the process of implementing it at the moment, but it's a nice possible future extension.

**Comment by seanmcl** [comment]
Too bad.  OK, thanks.
