### ISSUE TITLE
Live profiler question

### ISSUE THREAD

**Issue by seanmcl** [souffle-lang/souffle#725]
Are the -p and -l flags orthogonal?  

I ran `souffle -cl -p db_h2.prof db_h2.dl`, and needed to kill the program.  I expected there to be a file called `db_h2.prof` which I would then run `souffle-profile` on.  There is no .prof file though.  Is it possible to inspect the live profile after forcibly killing a run?

Thanks!

**Comment by b-scholz** [comment]
Can you try souffle -o db_h2 -l -p db_h2.prof db_h2.dl?
Run ./db_h2

The profiler prompt should appear immediately after invocation. Use top to check progress.

**Comment by b-scholz** [comment]
Yes - the live version is identical to the off-line version.

**Comment by seanmcl** [comment]
OK, that makes sense.  So you have to use the text interface for live profiling, and there's no record of the run once you kill the process except what appears in your terminal.  Right?

**Comment by b-scholz** [comment]
No - the profile should be stored in the specified file. 
You also have load/store instructions as well.

**Comment by seanmcl** [comment]
This is not my experience on OSX.  I can not get a `.prof` file to be generated when in live mode.  I tried all of the above, and a bunch of other combinations of flags.

**Comment by mmcgr** [comment]
The profile file is saved at the end of the run, independent of the live profiler. The load/store instructions were not implemented, so I recently removed the interface for them until they are. 

Usually if you interrupt the program, what you are most interested in is the currently executing rule, probably because it hasn't finished yet. However, profile information about that rule is not actually recorded until it is finished, so saving the profile will not help.

Profile information on a currently executing rule would slow it immensely, with the current implementation. What I would like to do is that if an interrupt is caught, interrupt rule execution, save the profile information so far, then save the log. That will make the saved log far more useful.

Note that if your main interest is 'which rule is currently executing', then the most efficient way is to run in verbose mode ( --verbose ). That has minimal effect on performance and will print out which rule is currently executing.
