### ISSUE TITLE
Optimization for Cross Products

### ISSUE THREAD

**Issue by b-scholz** [souffle-lang/souffle#733]
Assume we have a relation with a rule that computes a cross-product with constrains:
```
.decl A(x:number) input
.decl B(x:number) input

.decl R(x:number, y:number) 
R(x,y) :- A(x), B(y), x < 1000000, y <100000. 
```
which will effect the performance for very large relations A and B. We can rewrite the relation as follows:
```
.decl RA(x:number) 
RA(x) :- A(x), x < 1000000.

.decl RB(y:number)
RB(x) :- B(y), y <100000. 
```

If ```R(x,y)``` occurs in bodies of other rules, the predicate needs to be expanded by the conjunction ```RA(x), RB(y)```.

Finding separable relations with multiple rules is more complex since separable subsets of attributes must be found, that comply with the rules.

**Comment by b-scholz** [comment]
@azreika isn‘t that already implemented ? Can we close this issue?

**Comment by azreika** [comment]
No, this has not been implemented yet (although its related to existing ones), but I think it is an interesting one to consider. I think it can slow down the program in some cases, though - namely when the created subrelations are large, even with constraints.

The example I am working with:

```
a(x,y) :- b(x,z), c(z), d(y,r), e(r).
```
```
FOR ALL (x,z) IN b:
    IF (z) IN c:
        FOR ALL (y,r) IN d:
            IF (r) in e:
                ADD (x,y) TO a
```

This takes `O(|b||d|)` time.

`PartitionBodyLiterals` does not apply here because the head variables are dependent on all body variables. `x` and `y` are separable variables, though, because they don't dependent on each other, so we can still partition the cross product into:

```
a(x,y) :- a1(x), a2(y).
a1(x) :- b(x,z), c(z).
a2(y) :- d(y,r), e(r).
```
```
FOR ALL (x,z) IN b:
    IF (z) IN c:
        ADD (x) TO a1
FOR ALL (y,r) IN d:
    IF (r) in e:
        ADD (y) TO a2
FOR ALL (x) IN a1:
    FOR ALL (y) in a2:
          ADD (x,y) TO a
```

This takes `O(|b| + |d| + |a1||a2|)` time. If `a1` and `a2` are 'similar' in size to the original relations `b` and `d`, then we have just added the extra overhead 'copying over' most of the relations, without enough gain in the actual cross product. I think intuitively, for most programs where this is the case (especially those with several separable head variables), the benefits may outweight the overhead.
