### ISSUE TITLE
Souffle Parallel Performance

### ISSUE THREAD

**Issue by anantoni** [souffle-lang/souffle#755]
Hello,

It seems that commit 4c73a41a8c9ae8a4ca5aa9e7e88a4cb74386dc67: "Performance: removed utilization of parallel sections, causing performance degradation." has caused a performance loss that is close to  20% when running Souffle in parallel (when running with -j4 as an example). For instance, an analysis that used to take 1100-1200 seconds now runs in 1400-1500  seconds etc. I guess there is some reason behind this change, but are there any upcoming plans for performance improvements so that the performance will get closer to versions 1.3.0 and 1.3.1, while maintaining the current compilation speed?

Thanks,
Tony

**Comment by b-scholz** [comment]
That is interesting - can you send us the code/input that has this issue?

**Comment by HerbertJordan** [comment]
I build the current version and a version without the changes of the commit. On my test system, the analyses take 1098s and 1074s respectively (6-core Haswell system). So it seems like the performance difference is neglectable in my case.

I noticed, however, that when using only -j4 instead of -j6 (according to the 6 cores on my system) the version omitting 4c73a41, is faster (1406s vs. 1320s). This is because in the 4c73a41 version nested parallelism is utilized. Thus, actually more than 4 threads are used to run the analysis. In your case this has been beneficial, but in many other cases this lead to devastating performance reductions. Also, it is kind of cheating if you run it with -j4 and then it actually uses more threads. This is why 4c73a41 has been applied.

@anantoni can you check the number of threads you have it running with and how man your system actually offers? As you see, using all 6 instead of 4 threads on my sytem got me a ~40% reduction in execution time, and the performance difference between this and the modified version fanished.

**Comment by anantoni** [comment]
@HerbertJordan  Ι run it with -j4, which we decided was a good default for Doop back in 2017. I run Doop on a server with 24 cores (48 threads) so based on what you say it was using a lot more threads than the 4 I wanted before commit `4c73a41`? I understand your explanation so the only question I have is whether it is possible to have nested parallelism enabled only when a sufficient number of threads is given with -j or it is something that's totally out of your control and the only way to have the correct number of threads running was to remove it entirely. Thanks!

**Comment by b-scholz** [comment]
Can you change the number of threads with -j<nr> ? 
That might be the easiest solution for your system.

**Comment by anantoni** [comment]
Yes, we can that's not a problem. I just remember that in the past increasing the number of threads to 6 or 8 was not that beneficial (or sometimes not at all beneficial), so maybe we should re-evaluate the optimal number of threads for most analyses. Anyway, Herbert's response covered my question, since the change was has lead to correct behavior in terms of parallelism as opposed to the past versions.

**Comment by HerbertJordan** [comment]
It is always a good idea to experiment with the number of threads to see how it behaves. Do not stick to a option just because some day you decided this is a good option. Lot's of things changed in souffle and also it is very data and query dependent what a good option is. But at least it is not hard to experiment with that.

There is no option for you to re-enable nested parallelism. We could add this, but it would complicate matters, since you, as a user, would have to search a larger option space for a good setup. Note, that nested parallelism does not free you from tuning the -j option, as you can see in the data I listed above. I would thus ask to first investigate the situatoin and actually find a use case where having nested parallelism is indeed outperforming flat parallelism, with a properly adjusted value for the -j flag.

**Comment by anantoni** [comment]
Got it, thanks Herber and Bernhard.
