### ISSUE TITLE
Unknown encoding: C.UTF-8140574088297936

### ISSUE THREAD

**Issue by mjp41** [souffle-lang/souffle#828]
We have tried to use Souffle on the "Windows Subsystem for Linux", but received the following error message:

```
Unknown encoding: C.UTF-8140574088297936
```

The number after the `C.UTF-` various but the first few digits are stable.  This is with both the packages from Ubuntu, and building from source.  Any suggestions?

CC @sylvanc

**Comment by mmcgr** [comment]
That sounds like it might be an error from mcpp. That checks environment variables and expects to find a reasonably valid value in LC_ALL, LC_CTYPE, or LANG (checked in that order).

Check what is set in your environment.  I suspect you have something like `C.UTF-8` set, rather than just `C`, or a more complete `en_AU.UTF-8`. If I'm right, you can work around the error by setting LC_ALL to an acceptable value.

**Comment by mjp41** [comment]
You are correct:
```
$ echo $LANG
C.UTF-8
```
Setting `LANG=C` has unblocked me, thanks.
