### ISSUE TITLE
No debug report when souffle errors

### ISSUE THREAD

**Issue by olligobber** [souffle-lang/souffle#848]
When a program is not accepted by souffle, such as when a semantic check fails, it would be nice to have some output to the debug report (if the flag is set), perhaps to investigate why the failure occurred.

For example, when compiling the following program with `souffle --debug-report=x.html test.dl` it would be nice to see the type analysis to figure out why the constraint analysis could not determine the type of `x`.

```
.number_type N1
.number_type N2
.decl A(x : N1)
.decl B(x : N2)
.input A()
.output B()
A(x) :- B(x).
```

**Comment by lyndonhenry** [comment]
To me it seems that type errors are a compile time issue, or in the event of the interpreter being enabled, something that can be picked up before synthesis to the RAM program. 

So I feel it would be more appropriate to give said explanation at the command line, at execution time, rather than in the debug report. This would be an incredibly useful idea however, and allow uses to catch such bugs far earlier.

**Comment by lyndonhenry** [comment]
Oh, and as a postscript, I agree runtime errors however, should be left to the debug report.

**Comment by azreika** [comment]
To get around this, you can use `souffle -g --debug-report=x.html test.dl --disable-transformers=AstSemanticChecker`, which will disable the semantic checker and stop after translation to C code.

**Comment by olligobber** [comment]
It might be nice to get a partial debug report containing the early Ast transformers if a later transformer fails.

**Comment by olligobber** [comment]
That is a fair point, and the workaround @azreika suggested is sufficient for an advanced user.
