### ISSUE TITLE
Alternatives for OpenMP in Mac OS X

### ISSUE THREAD

**Issue by icesparrow** [souffle-lang/souffle#86]
Default OSX compilers do not provide openmp support. A potential solution is to grab an openmp implementation  (for instance [llvm openmp library](http://openmp.llvm.org/)) and build it before Soufflé is compiled.

**Comment by b-scholz** [comment]
With the standard CLANG compiler of XCODE this might be too hard to achieve because Apple did not compile CLANG with the OpenMP library. If this compiler configuration is too hard to be coerced into compiling OpenMP programs, I would just drop this issue and refer users to the instructions how to compile Souffle with brew.

What do you reckon?

**Comment by HerbertJordan** [comment]
Another option would be to exchange OpenMP by some `std::thread` based implementation, as it is supported by all C++11 compilers. 

However, this modification is a bit combersome, since you will have to implement some sort of thread pool and load management operations -- unless we use an external library to handle this for us.

**Comment by HerbertJordan** [comment]
Addon: I read in some mails that there was the idea to build OpenMP on the fly. I think, since OpenMP is tightly integrated into compilers and not just a library, that for this we will have to build the GCC or clang required for running it.

Switching to a `std::thread` approach would be, compared to sticking to OpenMP and build required compilers for the individual target platforms, a much smaller effort.

**Comment by b-scholz** [comment]
I agree that relying on standard threads would be easier in terms of build management because we would not rely on external software such as OpenMP that is not part of Apple's CLANG build
(delivered with XCODE). 

There is another alternative called CILK that we tried in the Oracle Labs. Unfortunately, it did not deliver the same performance as OpenMP (using GCC). However, for CLANG it could be a new alternative. The open source distribution can be found here:

https://cilkplus.github.io

but it might have similar problems, i.e., the Apple CLANG compiler does not support CILK out of the box. 

Herbert - are there any well-known libraries out there that support thread pooling and load management? It would be great to find some plug-and-play replacement for OpenMP.

If you agree, let's drop the effort of building the OpenMP library; let's search for alternatives. 

Kostyantyn - please could you rename the thread to "OpenMP alternatives"

**Comment by HerbertJordan** [comment]
One easy to integrate alternative is the parec library we have developed here in Innsbruck the last two years. It can handle nested parallelism and load imbalance just as well as cilk, while avoiding the introduction of task-overhead in case no tasks need to be created. It is a pure C++ std::thread based header-only implementation.

Link: https://github.com/HerbertJordan/parec

**Comment by b-scholz** [comment]
What is the impact on the performance and how long would it take to port the existing parallelisation to your library?

**Comment by HerbertJordan** [comment]
Performance wise it should be similar to OpenMP, but we will only know for sure once it is converted.

I also do not recommend to remove the cilk and OpenMP version, since in our current setup we can blend in analysis in the parallelization scheme of the surrounding host code. If it uses OpenMP, our code uses OpenMP, if it uses Cilk, our code uses Cilk.

But we can add it as the default system if nothing else is defined.

One restriction: the library is based on C++14 features (used to be C++11 a few weeks ago, but new features needed it)

To implement it is not very complex. I think i can do it in two days.

**Comment by b-scholz** [comment]
Perhaps we defer this issue for the next release.

**Comment by b-scholz** [comment]
Nathan mentioned that there is a thread pooling system under MAC OS X called "Great Central Dispatch" (GCD) that is also available under Linux (aka. libdispatch). I believe it has all the necessary features to cope with our load balancing / thread pooling tasks.

**Comment by b-scholz** [comment]
I found this very interesting blog entry. 
https://xenakios.wordpress.com/2014/09/29/concurrency-in-c-the-cross-platform-way/

I wonder whether we could use the proposed code idioms.

**Comment by HerbertJordan** [comment]
The prec library is targeting the same kind of interface -- essentially offering a pfor operator. But It does not map to any OS specific underlying infrastructure. It uses the portable async infrastructure, and adds its own thread and task management on top of it. Furthermore, it specializes task implementations depending on whether the associated workload should be processed in parallel or sequential -- potentially for each nested context, dynamically using  template based multi-versioning.

**Comment by b-scholz** [comment]
Would it work out of the box for MAC OS X?

**Comment by HerbertJordan** [comment]
It has no OS dependencies, so I am quite confident. I am also testing it with clang using the CI tools of github and locally. With those, it works fine. (I have no Mac).

**Comment by HerbertJordan** [comment]
If somebody has a Mac, can you clone the project and run the unit tests? Then we would know.

https://github.com/HerbertJordan/parec

**Comment by psubotic** [comment]
Im finding Openmp very painful with jni. I would be willing to help out if soemone would like to work on porting to c++.11 threads.

**Comment by mmcgr** [comment]
clang provided by xcode does not support openmp, but the gcc installed by homebrew does (with recent versions).
