### ISSUE TITLE
Datalog code in debug report sometimes not runnable

### ISSUE THREAD

**Issue by azreika** [souffle-lang/souffle#861]
Sometimes, the intermediate Datalog code shown in the debug report after each AST transform is not runnable, because the variable names used are not valid Souffle identifiers.

E.g.

```
.pragma "magic-transform" "*"

.decl a(x:number)
a(0).

.decl b(x:number)
b(x) :- a(x).
.output b()
```

produces the following code in the debug report after the magic-set transformation:

```
// ----- Types -----

// ----- Functors -----

// ----- Relations -----


// -- +m0_b+_f --
.decl +m0_b+_f() 

+m0_b+_f().



// -- a --
.decl a(x:number) 

a(0).



// -- b --
.decl b(x:number) output 

b(arg0) :- 
   b+_f(arg0).

.output {}()

.output {b}()



// -- b+_f --
.decl b+_f(x:number) 

b+_f(x) :- 
   +m0_b+_f(),
   a(x).


// ----- Pragma -----
magic-transform "*"
```

where identifiers have plus-signs in them, making them invalid.

The same sometimes happens with alias resolution and provenance.

**Comment by mmcgr** [comment]
Datalog output is almost runnable now. The problems remaining are

1. Ast transformations that generate a new name - either the generated name potentially clashes ("relationNameTransformed1"), an unused generated name is searched for, or we generate names that are not valid strings.
2. There are no CI tests to ensure the datalog stays runnable.

Solutions:
1. Since we already create lists of names as part of standard processing it would not be hard to make names like "RelationName_transformName_1234" and increment the number until a free name is found. This is similar to the current process for generating names. We do generate many names that have lost meaning, though, such as "disconnected01".
2. CI would ensure this feature keeps working, and also ensure that the output is useful (e.g. a copy paste error for a new Ast type prints out the old text)

If we do want to have valid,useful datalog output, we could also consider modifying Ast transformations to add comments to the datalog to explain the change/reasons for the change.

Solutions 2:
1. Leave it to the user to generate new, valid, names from the souffle output.
2. Hope it keeps working, and leave it to the user to identify/fix unclear/incorrect output.


We can implement the second solution right now by closing this issue. The first solution requires a few hours of work for each part.

**Comment by b-scholz** [comment]
This is mostly done with the refactoring.
