### ISSUE TITLE
Failing to use C++ interface

### ISSUE THREAD

**Issue by karljs** [souffle-lang/souffle#895]
I'm struggling to get the C++ interface to work in anything but a trivial project structure, and the documentation does not make clear what needs to happen for `ProgramFactory::newInstance()` to succeed.  Here's the dilemma:

I create a `trivial.dl` file:
```
.decl edge(x : number, y : number)
.decl path(x : number, y: number)
path(x, y) :- edge(x, y).
path(x, y) :- path(x, z), edge(z, y).
```
and a `main.cpp` as follows:
```
#include "souffle/SouffleInterface.h"
using namespace souffle;
int main(int argc, char **argv) {
  if (SouffleProgram *prog = ProgramFactory::newInstance("trivial")) {
    std::cout << "Success\n";
    delete prog;
  } else {
    std::cerr << "Failed to create instance for program trivial\n";
    exit(1);
  }
}
```
If I create a directory containing these two files, with all of the Souffle header files nested inside an include directory, I can run something like:
```
souffle trivial.dl -g trivial.cpp
clang++ main.cpp trivial.cpp -D__EMBEDDED_SOUFFLE__ -I./include
./a.out
```
And the program succeeds.

However, if I create a CMake project to build Souffle and my code against it, which uses these exact same files (in a different directory structure) then `newInstance("trivial")` fails.  

Am I missing something obvious?  From what I can tell, the Souffle C++ interface is header-only, and the only thing I can think is that maybe the parameter to `newInstance` needs to change, or something similar. 

Any advice to figuring this out would be greatly appreciated.  I'm not normally much of a C++ programmer, so digging through the source is kind of a slog.

**Comment by psubotic** [comment]
I reported this to Martin a few weeks ago -- also had the same problem. Can
someone please look into this?

**Comment by b-scholz** [comment]
Can you send us a tarball where this is happening?

**Comment by b-scholz** [comment]
Note we use constructors of global variables that are executed prior to main(). They must be executed otherwise you will not be able to find the instances.

If you are meddling with this in form of generating (dynamic loadable) libraries, the constructors won't be invoked and the newInstance() cannot find the instance. 

Basically, the C++ program has the following global instance 

```
static factory_Sf_<your-dl-name> __factory_Sf_<your-dl-name>_instance;
```

that calls the constructor  

```
ProgramFactory("<your-dl-name>") 
```

of your super-class.

I hope that helps.

**Comment by karljs** [comment]
@b-scholz Thanks for the info.  Unfortunately, my knowledge about C++ and CMake is pretty limited so I don't actually know what it's doing behind the scenes in terms of libraries.  I will do some experiments to see if I need to/can prevent it from building shared libraries.  I've attached a zip of my trivial project that fails--note that it expects a checkout of souffle inside the submodules directory.  Since this isn't a functioning git repo you'll have to do that manually.

[souffle-fail.zip](https://github.com/souffle-lang/souffle/files/2898596/souffle-fail.zip)

**Comment by b-scholz** [comment]
We found the issue. The issue is that you invoke souffle with a datalog file that is stored in a directory. Souffle prepends the directory path to the name and hence you cannot create a new instance.

A quick fix is to check your file trivial.cpp and search for the second occurrence of ProgramFactory("<my-string>"). 

Please use <my-string> for creating a new instance.

We need to fix this so that the name does not contain the directory structure as a prefix.

**Comment by karljs** [comment]
Thanks, I really appreciate the quick investigation.  I'll follow the PR and please feel free to close once it's merged.
